<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvincesAndCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $province = Province::create(['name' => 'اردبیل']);
        City::create(['name' => "اردبیل ", 'province_id' => $province->id]);
        City::create(['name' => "اصلاندوز ", 'province_id' => $province->id]);
        City::create(['name' => "آبی بیگلو ", 'province_id' => $province->id]);
        City::create(['name' => "بیله سوار ", 'province_id' => $province->id]);
        City::create(['name' => "پارس آباد ", 'province_id' => $province->id]);
        City::create(['name' => "تازه کند ", 'province_id' => $province->id]);
        City::create(['name' => "تازه کندانگوت ", 'province_id' => $province->id]);
        City::create(['name' => "جعفرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "خلخال ", 'province_id' => $province->id]);
        City::create(['name' => "رضی ", 'province_id' => $province->id]);
        City::create(['name' => "سرعین ", 'province_id' => $province->id]);
        City::create(['name' => "عنبران ", 'province_id' => $province->id]);
        City::create(['name' => "فخرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "کلور ", 'province_id' => $province->id]);
        City::create(['name' => "کوراییم ", 'province_id' => $province->id]);
        City::create(['name' => "گرمی ", 'province_id' => $province->id]);
        City::create(['name' => "گیوی ", 'province_id' => $province->id]);
        City::create(['name' => "لاهرود ", 'province_id' => $province->id]);
        City::create(['name' => "مرادلو ", 'province_id' => $province->id]);
        City::create(['name' => "مشگین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "نمین ", 'province_id' => $province->id]);
        City::create(['name' => "نیر ", 'province_id' => $province->id]);
        City::create(['name' => "هشتجین ", 'province_id' => $province->id]);
        City::create(['name' => "هیر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'اصفهان']);
        City::create(['name' => "ابریشم ", 'province_id' => $province->id]);
        City::create(['name' => "ابوزیدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "اردستان ", 'province_id' => $province->id]);
        City::create(['name' => "اژیه ", 'province_id' => $province->id]);
        City::create(['name' => "اصفهان ", 'province_id' => $province->id]);
        City::create(['name' => "افوس ", 'province_id' => $province->id]);
        City::create(['name' => "انارک ", 'province_id' => $province->id]);
        City::create(['name' => "ایمانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "آران وبیدگل ", 'province_id' => $province->id]);
        City::create(['name' => "بادرود ", 'province_id' => $province->id]);
        City::create(['name' => "باغ بهادران ", 'province_id' => $province->id]);
        City::create(['name' => "بافران ", 'province_id' => $province->id]);
        City::create(['name' => "برزک ", 'province_id' => $province->id]);
        City::create(['name' => "برف انبار ", 'province_id' => $province->id]);
        City::create(['name' => "بوئین ومیاندشت ", 'province_id' => $province->id]);
        City::create(['name' => "بهاران شهر ", 'province_id' => $province->id]);
        City::create(['name' => "بهارستان ", 'province_id' => $province->id]);
        City::create(['name' => "پیربکران ", 'province_id' => $province->id]);
        City::create(['name' => "تودشک ", 'province_id' => $province->id]);
        City::create(['name' => "تیران ", 'province_id' => $province->id]);
        City::create(['name' => "جندق ", 'province_id' => $province->id]);
        City::create(['name' => "جوزدان ", 'province_id' => $province->id]);
        City::create(['name' => "جوشقان وکامو ", 'province_id' => $province->id]);
        City::create(['name' => "چادگان ", 'province_id' => $province->id]);
        City::create(['name' => "چرمهین ", 'province_id' => $province->id]);
        City::create(['name' => "چمگردان ", 'province_id' => $province->id]);
        City::create(['name' => "حبیب آباد ", 'province_id' => $province->id]);
        City::create(['name' => "حسن آباد ", 'province_id' => $province->id]);
        City::create(['name' => "حنا ", 'province_id' => $province->id]);
        City::create(['name' => "خالدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "خمینی شهر ", 'province_id' => $province->id]);
        City::create(['name' => "خوانسار ", 'province_id' => $province->id]);
        City::create(['name' => "خور ", 'province_id' => $province->id]);
        City::create(['name' => "خوراسگان ", 'province_id' => $province->id]);
        City::create(['name' => "خورزوق ", 'province_id' => $province->id]);
        City::create(['name' => "داران ", 'province_id' => $province->id]);
        City::create(['name' => "دامنه ", 'province_id' => $province->id]);
        City::create(['name' => "درچه پیاز ", 'province_id' => $province->id]);
        City::create(['name' => "دستگرد ", 'province_id' => $province->id]);
        City::create(['name' => "دولت آباد ", 'province_id' => $province->id]);
        City::create(['name' => "دهاقان ", 'province_id' => $province->id]);
        City::create(['name' => "دهق ", 'province_id' => $province->id]);
        City::create(['name' => "دیزیچه ", 'province_id' => $province->id]);
        City::create(['name' => "رزوه ", 'province_id' => $province->id]);
        City::create(['name' => "رضوانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "زاینده رود ", 'province_id' => $province->id]);
        City::create(['name' => "زرین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "زواره ", 'province_id' => $province->id]);
        City::create(['name' => "زیباشهر ", 'province_id' => $province->id]);
        City::create(['name' => "سده لنجان ", 'province_id' => $province->id]);
        City::create(['name' => "سفیدشهر ", 'province_id' => $province->id]);
        City::create(['name' => "سگزی ", 'province_id' => $province->id]);
        City::create(['name' => "سمیرم ", 'province_id' => $province->id]);
        City::create(['name' => "شاپورآباد ", 'province_id' => $province->id]);
        City::create(['name' => "شاهین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "شهرضا ", 'province_id' => $province->id]);
        City::create(['name' => "طالخونچه ", 'province_id' => $province->id]);
        City::create(['name' => "عسگران ", 'province_id' => $province->id]);
        City::create(['name' => "علویچه ", 'province_id' => $province->id]);
        City::create(['name' => "فرخی ", 'province_id' => $province->id]);
        City::create(['name' => "فریدونشهر ", 'province_id' => $province->id]);
        City::create(['name' => "فلاورجان ", 'province_id' => $province->id]);
        City::create(['name' => "فولادشهر ", 'province_id' => $province->id]);
        City::create(['name' => "قمصر ", 'province_id' => $province->id]);
        City::create(['name' => "قهجاورستان ", 'province_id' => $province->id]);
        City::create(['name' => "قهدریجان ", 'province_id' => $province->id]);
        City::create(['name' => "کاشان ", 'province_id' => $province->id]);
        City::create(['name' => "کرکوند ", 'province_id' => $province->id]);
        City::create(['name' => "کلیشادوسودرجان ", 'province_id' => $province->id]);
        City::create(['name' => "کمشچه ", 'province_id' => $province->id]);
        City::create(['name' => "کمه ", 'province_id' => $province->id]);
        City::create(['name' => "کوشک ", 'province_id' => $province->id]);
        City::create(['name' => "کوهپایه ", 'province_id' => $province->id]);
        City::create(['name' => "کهریزسنگ ", 'province_id' => $province->id]);
        City::create(['name' => "گرگاب ", 'province_id' => $province->id]);
        City::create(['name' => "گزبرخوار ", 'province_id' => $province->id]);
        City::create(['name' => "گلپایگان ", 'province_id' => $province->id]);
        City::create(['name' => "گلدشت ", 'province_id' => $province->id]);
        City::create(['name' => "گلشن ", 'province_id' => $province->id]);
        City::create(['name' => "گلشهر ", 'province_id' => $province->id]);
        City::create(['name' => "گوگد ", 'province_id' => $province->id]);
        City::create(['name' => "لای بید ", 'province_id' => $province->id]);
        City::create(['name' => "مبارکه ", 'province_id' => $province->id]);
        City::create(['name' => "محمدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "مشکات ", 'province_id' => $province->id]);
        City::create(['name' => "منظریه ", 'province_id' => $province->id]);
        City::create(['name' => "مهاباد ", 'province_id' => $province->id]);
        City::create(['name' => "میمه ", 'province_id' => $province->id]);
        City::create(['name' => "نائین ", 'province_id' => $province->id]);
        City::create(['name' => "نجف آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نصرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "نطنز ", 'province_id' => $province->id]);
        City::create(['name' => "نوش آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نیاسر ", 'province_id' => $province->id]);
        City::create(['name' => "نیک آباد ", 'province_id' => $province->id]);
        City::create(['name' => "ورزنه ", 'province_id' => $province->id]);
        City::create(['name' => "ورنامخواست ", 'province_id' => $province->id]);
        City::create(['name' => "وزوان ", 'province_id' => $province->id]);
        City::create(['name' => "ونک ", 'province_id' => $province->id]);
        City::create(['name' => "هرند", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'البرز']);
        City::create(['name' => "اشتهارد ", 'province_id' => $province->id]);
        City::create(['name' => "آسارا ", 'province_id' => $province->id]);
        City::create(['name' => "تنکمان ", 'province_id' => $province->id]);
        City::create(['name' => "چهارباغ ", 'province_id' => $province->id]);
        City::create(['name' => "سیف آباد ", 'province_id' => $province->id]);
        City::create(['name' => "شهرجدیدهشتگرد ", 'province_id' => $province->id]);
        City::create(['name' => "طالقان ", 'province_id' => $province->id]);
        City::create(['name' => "کرج ", 'province_id' => $province->id]);
        City::create(['name' => "کمال شهر ", 'province_id' => $province->id]);
        City::create(['name' => "کوهسار ", 'province_id' => $province->id]);
        City::create(['name' => "گرمدره ", 'province_id' => $province->id]);
        City::create(['name' => "ماهدشت ", 'province_id' => $province->id]);
        City::create(['name' => "محمدشهر ", 'province_id' => $province->id]);
        City::create(['name' => "مشکین دشت ", 'province_id' => $province->id]);
        City::create(['name' => "نظرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "هشتگرد", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'ایلام']);
        City::create(['name' => "ارکواز ", 'province_id' => $province->id]);
        City::create(['name' => "ایلام ", 'province_id' => $province->id]);
        City::create(['name' => "ایوان ", 'province_id' => $province->id]);
        City::create(['name' => "آبدانان ", 'province_id' => $province->id]);
        City::create(['name' => "آسمان آباد ", 'province_id' => $province->id]);
        City::create(['name' => "بدره ", 'province_id' => $province->id]);
        City::create(['name' => "پهله ", 'province_id' => $province->id]);
        City::create(['name' => "توحید ", 'province_id' => $province->id]);
        City::create(['name' => "چوار ", 'province_id' => $province->id]);
        City::create(['name' => "دره شهر ", 'province_id' => $province->id]);
        City::create(['name' => "دلگشا ", 'province_id' => $province->id]);
        City::create(['name' => "دهلران ", 'province_id' => $province->id]);
        City::create(['name' => "زرنه ", 'province_id' => $province->id]);
        City::create(['name' => "سراب باغ ", 'province_id' => $province->id]);
        City::create(['name' => "سرابله ", 'province_id' => $province->id]);
        City::create(['name' => "صالح آباد ", 'province_id' => $province->id]);
        City::create(['name' => "لومار ", 'province_id' => $province->id]);
        City::create(['name' => "مورموری ", 'province_id' => $province->id]);
        City::create(['name' => "موسیان ", 'province_id' => $province->id]);
        City::create(['name' => "مهران ", 'province_id' => $province->id]);
        City::create(['name' => "میمه", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'آذربایجان شرقی']);
        City::create(['name' => "اسکو ", 'province_id' => $province->id]);
        City::create(['name' => "اهر ", 'province_id' => $province->id]);
        City::create(['name' => "ایلخچی ", 'province_id' => $province->id]);
        City::create(['name' => "آبش احمد ", 'province_id' => $province->id]);
        City::create(['name' => "آذرشهر ", 'province_id' => $province->id]);
        City::create(['name' => "آقکند ", 'province_id' => $province->id]);
        City::create(['name' => "باسمنج ", 'province_id' => $province->id]);
        City::create(['name' => "بخشایش ", 'province_id' => $province->id]);
        City::create(['name' => "بستان آباد ", 'province_id' => $province->id]);
        City::create(['name' => "بناب ", 'province_id' => $province->id]);
        City::create(['name' => "بناب جدید ", 'province_id' => $province->id]);
        City::create(['name' => "تبریز ", 'province_id' => $province->id]);
        City::create(['name' => "ترک ", 'province_id' => $province->id]);
        City::create(['name' => "ترکمانچای ", 'province_id' => $province->id]);
        City::create(['name' => "تسوج ", 'province_id' => $province->id]);
        City::create(['name' => "تیکمه داش ", 'province_id' => $province->id]);
        City::create(['name' => "جلفا ", 'province_id' => $province->id]);
        City::create(['name' => "خاروانا ", 'province_id' => $province->id]);
        City::create(['name' => "خامنه ", 'province_id' => $province->id]);
        City::create(['name' => "خراجو ", 'province_id' => $province->id]);
        City::create(['name' => "خسروشهر ", 'province_id' => $province->id]);
        City::create(['name' => "خمارلو ", 'province_id' => $province->id]);
        City::create(['name' => "خواجه ", 'province_id' => $province->id]);
        City::create(['name' => "دوزدوزان ", 'province_id' => $province->id]);
        City::create(['name' => "زرنق ", 'province_id' => $province->id]);
        City::create(['name' => "زنوز ", 'province_id' => $province->id]);
        City::create(['name' => "سراب ", 'province_id' => $province->id]);
        City::create(['name' => "سردرود ", 'province_id' => $province->id]);
        City::create(['name' => "سیس ", 'province_id' => $province->id]);
        City::create(['name' => "سیه رود ", 'province_id' => $province->id]);
        City::create(['name' => "شبستر ", 'province_id' => $province->id]);
        City::create(['name' => "شربیان ", 'province_id' => $province->id]);
        City::create(['name' => "شرفخانه ", 'province_id' => $province->id]);
        City::create(['name' => "شندآباد ", 'province_id' => $province->id]);
        City::create(['name' => "شهرجدیدسهند ", 'province_id' => $province->id]);
        City::create(['name' => "صوفیان ", 'province_id' => $province->id]);
        City::create(['name' => "عجب شیر ", 'province_id' => $province->id]);
        City::create(['name' => "قره آغاج ", 'province_id' => $province->id]);
        City::create(['name' => "کشکسرای ", 'province_id' => $province->id]);
        City::create(['name' => "کلوانق ", 'province_id' => $province->id]);
        City::create(['name' => "کلیبر ", 'province_id' => $province->id]);
        City::create(['name' => "کوزه کنان ", 'province_id' => $province->id]);
        City::create(['name' => "گوگان ", 'province_id' => $province->id]);
        City::create(['name' => "لیلان ", 'province_id' => $province->id]);
        City::create(['name' => "مراغه ", 'province_id' => $province->id]);
        City::create(['name' => "مرند ", 'province_id' => $province->id]);
        City::create(['name' => "ملکان ", 'province_id' => $province->id]);
        City::create(['name' => "ممقان ", 'province_id' => $province->id]);
        City::create(['name' => "مهربان ", 'province_id' => $province->id]);
        City::create(['name' => "میانه ", 'province_id' => $province->id]);
        City::create(['name' => "نظرکهریزی ", 'province_id' => $province->id]);
        City::create(['name' => "وایقان ", 'province_id' => $province->id]);
        City::create(['name' => "ورزقان ", 'province_id' => $province->id]);
        City::create(['name' => "هادیشهر ", 'province_id' => $province->id]);
        City::create(['name' => "هریس ", 'province_id' => $province->id]);
        City::create(['name' => "هشترود ", 'province_id' => $province->id]);
        City::create(['name' => "هوراند ", 'province_id' => $province->id]);
        City::create(['name' => "یامچی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'آذربایجان غربی']);
        City::create(['name' => "ارومیه ", 'province_id' => $province->id]);
        City::create(['name' => "اشنویه ", 'province_id' => $province->id]);
        City::create(['name' => "ایواوغلی ", 'province_id' => $province->id]);
        City::create(['name' => "آواجیق ", 'province_id' => $province->id]);
        City::create(['name' => "باروق ", 'province_id' => $province->id]);
        City::create(['name' => "بازرگان ", 'province_id' => $province->id]);
        City::create(['name' => "بوکان ", 'province_id' => $province->id]);
        City::create(['name' => "پلدشت ", 'province_id' => $province->id]);
        City::create(['name' => "پیرانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "تازه شهر ", 'province_id' => $province->id]);
        City::create(['name' => "تکاب ", 'province_id' => $province->id]);
        City::create(['name' => "چهاربرج ", 'province_id' => $province->id]);
        City::create(['name' => "خلیفان ", 'province_id' => $province->id]);
        City::create(['name' => "خوی ", 'province_id' => $province->id]);
        City::create(['name' => "دیزج دیز ", 'province_id' => $province->id]);
        City::create(['name' => "ربط ", 'province_id' => $province->id]);
        City::create(['name' => "سردشت ", 'province_id' => $province->id]);
        City::create(['name' => "سرو ", 'province_id' => $province->id]);
        City::create(['name' => "سلماس ", 'province_id' => $province->id]);
        City::create(['name' => "سیلوانه ", 'province_id' => $province->id]);
        City::create(['name' => "سیمینه ", 'province_id' => $province->id]);
        City::create(['name' => "سیه چشمه ", 'province_id' => $province->id]);
        City::create(['name' => "شاهین دژ ", 'province_id' => $province->id]);
        City::create(['name' => "شوط ", 'province_id' => $province->id]);
        City::create(['name' => "فیرورق ", 'province_id' => $province->id]);
        City::create(['name' => "قره ضیاءالدین ", 'province_id' => $province->id]);
        City::create(['name' => "قطور ", 'province_id' => $province->id]);
        City::create(['name' => "قوشچی ", 'province_id' => $province->id]);
        City::create(['name' => "کشاورز ", 'province_id' => $province->id]);
        City::create(['name' => "گردکشانه ", 'province_id' => $province->id]);
        City::create(['name' => "ماکو ", 'province_id' => $province->id]);
        City::create(['name' => "محمدیار ", 'province_id' => $province->id]);
        City::create(['name' => "محمودآباد ", 'province_id' => $province->id]);
        City::create(['name' => "مهاباد ", 'province_id' => $province->id]);
        City::create(['name' => "میاندوآب ", 'province_id' => $province->id]);
        City::create(['name' => "میرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "نالوس ", 'province_id' => $province->id]);
        City::create(['name' => "نقده ", 'province_id' => $province->id]);
        City::create(['name' => "نوشین", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'بوشهر']);

        City::create(['name' => "امام حسن ", 'province_id' => $province->id]);
        City::create(['name' => "انارستان ", 'province_id' => $province->id]);
        City::create(['name' => "اهرم ", 'province_id' => $province->id]);
        City::create(['name' => "آبپخش ", 'province_id' => $province->id]);
        City::create(['name' => "آبدان ", 'province_id' => $province->id]);
        City::create(['name' => "برازجان ", 'province_id' => $province->id]);
        City::create(['name' => "بردخون ", 'province_id' => $province->id]);
        City::create(['name' => "بردستان ", 'province_id' => $province->id]);
        City::create(['name' => "بندردیر ", 'province_id' => $province->id]);
        City::create(['name' => "بندردیلم ", 'province_id' => $province->id]);
        City::create(['name' => "بندرریگ ", 'province_id' => $province->id]);
        City::create(['name' => "بندرکنگان ", 'province_id' => $province->id]);
        City::create(['name' => "بندرگناوه ", 'province_id' => $province->id]);
        City::create(['name' => "بنک ", 'province_id' => $province->id]);
        City::create(['name' => "بوشهر ", 'province_id' => $province->id]);
        City::create(['name' => "تنگ ارم ", 'province_id' => $province->id]);
        City::create(['name' => "جم ", 'province_id' => $province->id]);
        City::create(['name' => "چغادک ", 'province_id' => $province->id]);
        City::create(['name' => "خارک ", 'province_id' => $province->id]);
        City::create(['name' => "خورموج ", 'province_id' => $province->id]);
        City::create(['name' => "دالکی ", 'province_id' => $province->id]);
        City::create(['name' => "دلوار ", 'province_id' => $province->id]);
        City::create(['name' => "ریز ", 'province_id' => $province->id]);
        City::create(['name' => "سعدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "سیراف ", 'province_id' => $province->id]);
        City::create(['name' => "شبانکاره ", 'province_id' => $province->id]);
        City::create(['name' => "شنبه ", 'province_id' => $province->id]);
        City::create(['name' => "عسلویه ", 'province_id' => $province->id]);
        City::create(['name' => "کاکی ", 'province_id' => $province->id]);
        City::create(['name' => "کلمه ", 'province_id' => $province->id]);
        City::create(['name' => "نخل تقی ", 'province_id' => $province->id]);
        City::create(['name' => "وحدتیه", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'تهران']);

        City::create(['name' => "ارجمند ", 'province_id' => $province->id]);
        City::create(['name' => "اسلامشهر ", 'province_id' => $province->id]);
        City::create(['name' => "اندیشه ", 'province_id' => $province->id]);
        City::create(['name' => "آبسرد ", 'province_id' => $province->id]);
        City::create(['name' => "آبعلی ", 'province_id' => $province->id]);
        City::create(['name' => "باغستان ", 'province_id' => $province->id]);
        City::create(['name' => "باقرشهر ", 'province_id' => $province->id]);
        City::create(['name' => "بومهن ", 'province_id' => $province->id]);
        City::create(['name' => "پاکدشت ", 'province_id' => $province->id]);
        City::create(['name' => "پردیس ", 'province_id' => $province->id]);
        City::create(['name' => "پیشوا ", 'province_id' => $province->id]);
        City::create(['name' => "تجریش ", 'province_id' => $province->id]);
        City::create(['name' => "تهران ", 'province_id' => $province->id]);
        City::create(['name' => "جوادآباد ", 'province_id' => $province->id]);
        City::create(['name' => "چهاردانگه ", 'province_id' => $province->id]);
        City::create(['name' => "حسن آباد ", 'province_id' => $province->id]);
        City::create(['name' => "دماوند ", 'province_id' => $province->id]);
        City::create(['name' => "رباط کریم ", 'province_id' => $province->id]);
        City::create(['name' => "رودهن ", 'province_id' => $province->id]);
        City::create(['name' => "ری ", 'province_id' => $province->id]);
        City::create(['name' => "شاهدشهر ", 'province_id' => $province->id]);
        City::create(['name' => "شریف آباد ", 'province_id' => $province->id]);
        City::create(['name' => "شهریار ", 'province_id' => $province->id]);
        City::create(['name' => "صالح آباد ", 'province_id' => $province->id]);
        City::create(['name' => "صباشهر ", 'province_id' => $province->id]);
        City::create(['name' => "صفادشت ", 'province_id' => $province->id]);
        City::create(['name' => "فردوسیه ", 'province_id' => $province->id]);
        City::create(['name' => "فرون آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فشم ", 'province_id' => $province->id]);
        City::create(['name' => "فیروزکوه ", 'province_id' => $province->id]);
        City::create(['name' => "قدس ", 'province_id' => $province->id]);
        City::create(['name' => "قرچک ", 'province_id' => $province->id]);
        City::create(['name' => "کهریزک ", 'province_id' => $province->id]);
        City::create(['name' => "کیلان ", 'province_id' => $province->id]);
        City::create(['name' => "گلستان ", 'province_id' => $province->id]);
        City::create(['name' => "لواسان ", 'province_id' => $province->id]);
        City::create(['name' => "ملارد ", 'province_id' => $province->id]);
        City::create(['name' => "نسیم شهر ", 'province_id' => $province->id]);
        City::create(['name' => "نصیرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "وحیدیه ", 'province_id' => $province->id]);
        City::create(['name' => "ورامین", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'چهارمحال وبختیاری']);

        City::create(['name' => "اردل ", 'province_id' => $province->id]);
        City::create(['name' => "آلونی ", 'province_id' => $province->id]);
        City::create(['name' => "باباحیدر ", 'province_id' => $province->id]);
        City::create(['name' => "بروجن ", 'province_id' => $province->id]);
        City::create(['name' => "بلداجی ", 'province_id' => $province->id]);
        City::create(['name' => "بن ", 'province_id' => $province->id]);
        City::create(['name' => "جونقان ", 'province_id' => $province->id]);
        City::create(['name' => "چلگرد ", 'province_id' => $province->id]);
        City::create(['name' => "سامان ", 'province_id' => $province->id]);
        City::create(['name' => "سفیددشت ", 'province_id' => $province->id]);
        City::create(['name' => "سودجان ", 'province_id' => $province->id]);
        City::create(['name' => "سورشجان ", 'province_id' => $province->id]);
        City::create(['name' => "شلمزار ", 'province_id' => $province->id]);
        City::create(['name' => "شهرکرد ", 'province_id' => $province->id]);
        City::create(['name' => "طاقانک ", 'province_id' => $province->id]);
        City::create(['name' => "فارسان ", 'province_id' => $province->id]);
        City::create(['name' => "فرادنبه ", 'province_id' => $province->id]);
        City::create(['name' => "فرخ شهر ", 'province_id' => $province->id]);
        City::create(['name' => "کیان ", 'province_id' => $province->id]);
        City::create(['name' => "گندمان ", 'province_id' => $province->id]);
        City::create(['name' => "گهرو ", 'province_id' => $province->id]);
        City::create(['name' => "لردگان ", 'province_id' => $province->id]);
        City::create(['name' => "مال خلیفه ", 'province_id' => $province->id]);
        City::create(['name' => "ناغان ", 'province_id' => $province->id]);
        City::create(['name' => "نافچ ", 'province_id' => $province->id]);
        City::create(['name' => "نقنه ", 'province_id' => $province->id]);
        City::create(['name' => "هفشجان", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'خراسان جنوبی']);

        City::create(['name' => "ارسک ", 'province_id' => $province->id]);
        City::create(['name' => "اسدیه ", 'province_id' => $province->id]);
        City::create(['name' => "اسفدن ", 'province_id' => $province->id]);
        City::create(['name' => "اسلامیه ", 'province_id' => $province->id]);
        City::create(['name' => "آرین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "آیسک ", 'province_id' => $province->id]);
        City::create(['name' => "بشرویه ", 'province_id' => $province->id]);
        City::create(['name' => "بیرجند ", 'province_id' => $province->id]);
        City::create(['name' => "حاجی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خضری دشت بیاض ", 'province_id' => $province->id]);
        City::create(['name' => "خوسف ", 'province_id' => $province->id]);
        City::create(['name' => "زهان ", 'province_id' => $province->id]);
        City::create(['name' => "سرایان ", 'province_id' => $province->id]);
        City::create(['name' => "سربیشه ", 'province_id' => $province->id]);
        City::create(['name' => "سه قلعه ", 'province_id' => $province->id]);
        City::create(['name' => "شوسف ", 'province_id' => $province->id]);
        City::create(['name' => "طبس مسینا ", 'province_id' => $province->id]);
        City::create(['name' => "فردوس ", 'province_id' => $province->id]);
        City::create(['name' => "قائن ", 'province_id' => $province->id]);
        City::create(['name' => "قهستان ", 'province_id' => $province->id]);
        City::create(['name' => "گزیک ", 'province_id' => $province->id]);
        City::create(['name' => "محمد شهر ", 'province_id' => $province->id]);
        City::create(['name' => "مود ", 'province_id' => $province->id]);
        City::create(['name' => "نهبندان ", 'province_id' => $province->id]);
        City::create(['name' => "نیمبلوک", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'خراسان رضوی']);
        City::create(['name' => "احمدآبادصولت ", 'province_id' => $province->id]);
        City::create(['name' => "انابد ", 'province_id' => $province->id]);
        City::create(['name' => "باجگیران ", 'province_id' => $province->id]);
        City::create(['name' => "باخرز ", 'province_id' => $province->id]);
        City::create(['name' => "بار ", 'province_id' => $province->id]);
        City::create(['name' => "بایگ ", 'province_id' => $province->id]);
        City::create(['name' => "بجستان ", 'province_id' => $province->id]);
        City::create(['name' => "بردسکن ", 'province_id' => $province->id]);
        City::create(['name' => "بیدخت ", 'province_id' => $province->id]);
        City::create(['name' => "تایباد ", 'province_id' => $province->id]);
        City::create(['name' => "تربت جام ", 'province_id' => $province->id]);
        City::create(['name' => "تربت حیدریه ", 'province_id' => $province->id]);
        City::create(['name' => "جغتای ", 'province_id' => $province->id]);
        City::create(['name' => "جنگل ", 'province_id' => $province->id]);
        City::create(['name' => "چاپشلو ", 'province_id' => $province->id]);
        City::create(['name' => "چکنه ", 'province_id' => $province->id]);
        City::create(['name' => "چناران ", 'province_id' => $province->id]);
        City::create(['name' => "خرو ", 'province_id' => $province->id]);
        City::create(['name' => "خلیل آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خواف ", 'province_id' => $province->id]);
        City::create(['name' => "داورزن ", 'province_id' => $province->id]);
        City::create(['name' => "درگز ", 'province_id' => $province->id]);
        City::create(['name' => "درود ", 'province_id' => $province->id]);
        City::create(['name' => "دولت آباد ", 'province_id' => $province->id]);
        City::create(['name' => "رباط سنگ ", 'province_id' => $province->id]);
        City::create(['name' => "رشتخوار ", 'province_id' => $province->id]);
        City::create(['name' => "رضویه ", 'province_id' => $province->id]);
        City::create(['name' => "روداب ", 'province_id' => $province->id]);
        City::create(['name' => "ریوش ", 'province_id' => $province->id]);
        City::create(['name' => "سبزوار ", 'province_id' => $province->id]);
        City::create(['name' => "سرخس ", 'province_id' => $province->id]);
        City::create(['name' => "سفیدسنگ ", 'province_id' => $province->id]);
        City::create(['name' => "سلامی ", 'province_id' => $province->id]);
        City::create(['name' => "سلطان آباد ", 'province_id' => $province->id]);
        City::create(['name' => "سنگان ", 'province_id' => $province->id]);
        City::create(['name' => "شادمهر ", 'province_id' => $province->id]);
        City::create(['name' => "شاندیز ", 'province_id' => $province->id]);
        City::create(['name' => "ششتمد ", 'province_id' => $province->id]);
        City::create(['name' => "شهرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "شهرزو ", 'province_id' => $province->id]);
        City::create(['name' => "صالح آباد ", 'province_id' => $province->id]);
        City::create(['name' => "طرقبه ", 'province_id' => $province->id]);
        City::create(['name' => "عشق آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فرهادگرد ", 'province_id' => $province->id]);
        City::create(['name' => "فریمان ", 'province_id' => $province->id]);
        City::create(['name' => "فیروزه ", 'province_id' => $province->id]);
        City::create(['name' => "فیض آباد ", 'province_id' => $province->id]);
        City::create(['name' => "قاسم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "قدمگاه ", 'province_id' => $province->id]);
        City::create(['name' => "قلندرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "قوچان ", 'province_id' => $province->id]);
        City::create(['name' => "کاخک ", 'province_id' => $province->id]);
        City::create(['name' => "کاریز ", 'province_id' => $province->id]);
        City::create(['name' => "کاشمر ", 'province_id' => $province->id]);
        City::create(['name' => "کدکن ", 'province_id' => $province->id]);
        City::create(['name' => "کلات ", 'province_id' => $province->id]);
        City::create(['name' => "کندر ", 'province_id' => $province->id]);
        City::create(['name' => "گلمکان ", 'province_id' => $province->id]);
        City::create(['name' => "گناباد ", 'province_id' => $province->id]);
        City::create(['name' => "لطف آباد ", 'province_id' => $province->id]);
        City::create(['name' => "مزدآوند ", 'province_id' => $province->id]);
        City::create(['name' => "مشهد ", 'province_id' => $province->id]);
        City::create(['name' => "مشهدریزه ", 'province_id' => $province->id]);
        City::create(['name' => "ملک آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نشتیفان ", 'province_id' => $province->id]);
        City::create(['name' => "نصر آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نقاب ", 'province_id' => $province->id]);
        City::create(['name' => "نوخندان ", 'province_id' => $province->id]);
        City::create(['name' => "نیشابور ", 'province_id' => $province->id]);
        City::create(['name' => "نیل شهر ", 'province_id' => $province->id]);
        City::create(['name' => "همت آباد ", 'province_id' => $province->id]);
        City::create(['name' => "یونسی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'خراسان شمالی']);
        City::create(['name' => "اسفراین ", 'province_id' => $province->id]);
        City::create(['name' => "ایور ", 'province_id' => $province->id]);
        City::create(['name' => "آشخانه ", 'province_id' => $province->id]);
        City::create(['name' => "بجنورد ", 'province_id' => $province->id]);
        City::create(['name' => "پیش قلعه ", 'province_id' => $province->id]);
        City::create(['name' => "تیتکانلو ", 'province_id' => $province->id]);
        City::create(['name' => "جاجرم ", 'province_id' => $province->id]);
        City::create(['name' => "حصارگرمخان ", 'province_id' => $province->id]);
        City::create(['name' => "درق ", 'province_id' => $province->id]);
        City::create(['name' => "راز ", 'province_id' => $province->id]);
        City::create(['name' => "سنخواست ", 'province_id' => $province->id]);
        City::create(['name' => "شوقان ", 'province_id' => $province->id]);
        City::create(['name' => "شیروان ", 'province_id' => $province->id]);
        City::create(['name' => "صفی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فاروج ", 'province_id' => $province->id]);
        City::create(['name' => "قاضی ", 'province_id' => $province->id]);
        City::create(['name' => "گرمه ", 'province_id' => $province->id]);
        City::create(['name' => "لوجلی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'خوزستان']);
        City::create(['name' => "اروندکنار ", 'province_id' => $province->id]);
        City::create(['name' => "الوان ", 'province_id' => $province->id]);
        City::create(['name' => "امیدیه ", 'province_id' => $province->id]);
        City::create(['name' => "اندیمشک ", 'province_id' => $province->id]);
        City::create(['name' => "اهواز ", 'province_id' => $province->id]);
        City::create(['name' => "ایذه ", 'province_id' => $province->id]);
        City::create(['name' => "آبادان ", 'province_id' => $province->id]);
        City::create(['name' => "آغاجاری ", 'province_id' => $province->id]);
        City::create(['name' => "باغ ملک ", 'province_id' => $province->id]);
        City::create(['name' => "بستان ", 'province_id' => $province->id]);
        City::create(['name' => "بندرامام خمینی ", 'province_id' => $province->id]);
        City::create(['name' => "بندرماهشهر ", 'province_id' => $province->id]);
        City::create(['name' => "بهبهان ", 'province_id' => $province->id]);
        City::create(['name' => "ترکالکی ", 'province_id' => $province->id]);
        City::create(['name' => "جایزان ", 'province_id' => $province->id]);
        City::create(['name' => "جنت مکان ", 'province_id' => $province->id]);
        City::create(['name' => "چغامیش ", 'province_id' => $province->id]);
        City::create(['name' => "چمران ", 'province_id' => $province->id]);
        City::create(['name' => "چوئبده ", 'province_id' => $province->id]);
        City::create(['name' => "حر ", 'province_id' => $province->id]);
        City::create(['name' => "حسینیه ", 'province_id' => $province->id]);
        City::create(['name' => "حمزه ", 'province_id' => $province->id]);
        City::create(['name' => "حمیدیه ", 'province_id' => $province->id]);
        City::create(['name' => "خرمشهر ", 'province_id' => $province->id]);
        City::create(['name' => "دارخوین ", 'province_id' => $province->id]);
        City::create(['name' => "دزآب ", 'province_id' => $province->id]);
        City::create(['name' => "دزفول ", 'province_id' => $province->id]);
        City::create(['name' => "دهدز ", 'province_id' => $province->id]);
        City::create(['name' => "رامشیر ", 'province_id' => $province->id]);
        City::create(['name' => "رامهرمز ", 'province_id' => $province->id]);
        City::create(['name' => "رفیع ", 'province_id' => $province->id]);
        City::create(['name' => "زهره ", 'province_id' => $province->id]);
        City::create(['name' => "سالند ", 'province_id' => $province->id]);
        City::create(['name' => "سردشت ", 'province_id' => $province->id]);
        City::create(['name' => "سماله ", 'province_id' => $province->id]);
        City::create(['name' => "سوسنگرد ", 'province_id' => $province->id]);
        City::create(['name' => "شادگان ", 'province_id' => $province->id]);
        City::create(['name' => "شاوور ", 'province_id' => $province->id]);
        City::create(['name' => "شرافت ", 'province_id' => $province->id]);
        City::create(['name' => "شوش ", 'province_id' => $province->id]);
        City::create(['name' => "شوشتر ", 'province_id' => $province->id]);
        City::create(['name' => "شیبان ", 'province_id' => $province->id]);
        City::create(['name' => "صالح شهر ", 'province_id' => $province->id]);
        City::create(['name' => "صالح مشطط ", 'province_id' => $province->id]);
        City::create(['name' => "صفی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "صیدون ", 'province_id' => $province->id]);
        City::create(['name' => "قلعه تل ", 'province_id' => $province->id]);
        City::create(['name' => "قلعه خواجه ", 'province_id' => $province->id]);
        City::create(['name' => "گتوند ", 'province_id' => $province->id]);
        City::create(['name' => "گوریه ", 'province_id' => $province->id]);
        City::create(['name' => "لالی ", 'province_id' => $province->id]);
        City::create(['name' => "مسجدسلیمان ", 'province_id' => $province->id]);
        City::create(['name' => "مشراگه ", 'province_id' => $province->id]);
        City::create(['name' => "مقاومت ", 'province_id' => $province->id]);
        City::create(['name' => "ملاثانی ", 'province_id' => $province->id]);
        City::create(['name' => "میانرود ", 'province_id' => $province->id]);
        City::create(['name' => "میداود ", 'province_id' => $province->id]);
        City::create(['name' => "مینوشهر ", 'province_id' => $province->id]);
        City::create(['name' => "ویس ", 'province_id' => $province->id]);
        City::create(['name' => "هفتگل ", 'province_id' => $province->id]);
        City::create(['name' => "هندیجان ", 'province_id' => $province->id]);
        City::create(['name' => "هویزه", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'زنجان']);
        City::create(['name' => "ابهر ", 'province_id' => $province->id]);
        City::create(['name' => "ارمغانخانه ", 'province_id' => $province->id]);
        City::create(['name' => "آب بر ", 'province_id' => $province->id]);
        City::create(['name' => "چورزق ", 'province_id' => $province->id]);
        City::create(['name' => "حلب ", 'province_id' => $province->id]);
        City::create(['name' => "خرمدره ", 'province_id' => $province->id]);
        City::create(['name' => "دندی ", 'province_id' => $province->id]);
        City::create(['name' => "زرین آباد ", 'province_id' => $province->id]);
        City::create(['name' => "زرین رود ", 'province_id' => $province->id]);
        City::create(['name' => "زنجان ", 'province_id' => $province->id]);
        City::create(['name' => "سجاس ", 'province_id' => $province->id]);
        City::create(['name' => "سلطانیه ", 'province_id' => $province->id]);
        City::create(['name' => "سهرورد ", 'province_id' => $province->id]);
        City::create(['name' => "صائین قلعه ", 'province_id' => $province->id]);
        City::create(['name' => "قیدار ", 'province_id' => $province->id]);
        City::create(['name' => "گرماب ", 'province_id' => $province->id]);
        City::create(['name' => "ماه نشان ", 'province_id' => $province->id]);
        City::create(['name' => "هیدج", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'سمنان']);
        City::create(['name' => "امیریه ", 'province_id' => $province->id]);
        City::create(['name' => "ایوانکی ", 'province_id' => $province->id]);
        City::create(['name' => "آرادان ", 'province_id' => $province->id]);
        City::create(['name' => "بسطام ", 'province_id' => $province->id]);
        City::create(['name' => "بیارجمند ", 'province_id' => $province->id]);
        City::create(['name' => "دامغان ", 'province_id' => $province->id]);
        City::create(['name' => "درجزین ", 'province_id' => $province->id]);
        City::create(['name' => "دیباج ", 'province_id' => $province->id]);
        City::create(['name' => "سرخه ", 'province_id' => $province->id]);
        City::create(['name' => "سمنان ", 'province_id' => $province->id]);
        City::create(['name' => "شاهرود ", 'province_id' => $province->id]);
        City::create(['name' => "شهمیرزاد ", 'province_id' => $province->id]);
        City::create(['name' => "کلاته خیج ", 'province_id' => $province->id]);
        City::create(['name' => "گرمسار ", 'province_id' => $province->id]);
        City::create(['name' => "مجن ", 'province_id' => $province->id]);
        City::create(['name' => "مهدی شهر ", 'province_id' => $province->id]);
        City::create(['name' => "میامی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'سیستان وبلوچستان']);
        City::create(['name' => "ادیمی ", 'province_id' => $province->id]);
        City::create(['name' => "اسپکه ", 'province_id' => $province->id]);
        City::create(['name' => "ایرانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "بزمان ", 'province_id' => $province->id]);
        City::create(['name' => "بمپور ", 'province_id' => $province->id]);
        City::create(['name' => "بنت ", 'province_id' => $province->id]);
        City::create(['name' => "بنجار ", 'province_id' => $province->id]);
        City::create(['name' => "پیشین ", 'province_id' => $province->id]);
        City::create(['name' => "جالق ", 'province_id' => $province->id]);
        City::create(['name' => "چاه بهار ", 'province_id' => $province->id]);
        City::create(['name' => "خاش ", 'province_id' => $province->id]);
        City::create(['name' => "دوست محمد ", 'province_id' => $province->id]);
        City::create(['name' => "راسک ", 'province_id' => $province->id]);
        City::create(['name' => "زابل ", 'province_id' => $province->id]);
        City::create(['name' => "زابلی ", 'province_id' => $province->id]);
        City::create(['name' => "زاهدان ", 'province_id' => $province->id]);
        City::create(['name' => "زرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "زهک ", 'province_id' => $province->id]);
        City::create(['name' => "سراوان ", 'province_id' => $province->id]);
        City::create(['name' => "سرباز ", 'province_id' => $province->id]);
        City::create(['name' => "سوران ", 'province_id' => $province->id]);
        City::create(['name' => "سیرکان ", 'province_id' => $province->id]);
        City::create(['name' => "علی اکبر ", 'province_id' => $province->id]);
        City::create(['name' => "فنوج ", 'province_id' => $province->id]);
        City::create(['name' => "قصرقند ", 'province_id' => $province->id]);
        City::create(['name' => "کنارک ", 'province_id' => $province->id]);
        City::create(['name' => "گشت ", 'province_id' => $province->id]);
        City::create(['name' => "گلمورتی ", 'province_id' => $province->id]);
        City::create(['name' => "محمدان ", 'province_id' => $province->id]);
        City::create(['name' => "محمد آباد ", 'province_id' => $province->id]);
        City::create(['name' => "محمدی ", 'province_id' => $province->id]);
        City::create(['name' => "میرجاوه ", 'province_id' => $province->id]);
        City::create(['name' => "نصرت آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نگور ", 'province_id' => $province->id]);
        City::create(['name' => "نوک آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نیک شهر ", 'province_id' => $province->id]);
        City::create(['name' => "هیدوج", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'فارس']);
        City::create(['name' => "اردکان ", 'province_id' => $province->id]);
        City::create(['name' => "ارسنجان ", 'province_id' => $province->id]);
        City::create(['name' => "استهبان ", 'province_id' => $province->id]);
        City::create(['name' => "اسیر ", 'province_id' => $province->id]);
        City::create(['name' => "اشکنان ", 'province_id' => $province->id]);
        City::create(['name' => "افزر ", 'province_id' => $province->id]);
        City::create(['name' => "اقلید ", 'province_id' => $province->id]);
        City::create(['name' => "امام شهر ", 'province_id' => $province->id]);
        City::create(['name' => "اوز ", 'province_id' => $province->id]);
        City::create(['name' => "اهل ", 'province_id' => $province->id]);
        City::create(['name' => "ایج ", 'province_id' => $province->id]);
        City::create(['name' => "ایزدخواست ", 'province_id' => $province->id]);
        City::create(['name' => "آباده ", 'province_id' => $province->id]);
        City::create(['name' => "آباده طشک ", 'province_id' => $province->id]);
        City::create(['name' => "باب انار ", 'province_id' => $province->id]);
        City::create(['name' => "بالاده ", 'province_id' => $province->id]);
        City::create(['name' => "بنارویه ", 'province_id' => $province->id]);
        City::create(['name' => "بوانات ", 'province_id' => $province->id]);
        City::create(['name' => "بهمن ", 'province_id' => $province->id]);
        City::create(['name' => "بیرم ", 'province_id' => $province->id]);
        City::create(['name' => "بیضا ", 'province_id' => $province->id]);
        City::create(['name' => "جنت شهر ", 'province_id' => $province->id]);
        City::create(['name' => "جویم ", 'province_id' => $province->id]);
        City::create(['name' => "جهرم ", 'province_id' => $province->id]);
        City::create(['name' => "حاجی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "حسامی ", 'province_id' => $province->id]);
        City::create(['name' => "حسن آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خانه زنیان ", 'province_id' => $province->id]);
        City::create(['name' => "خاوران ", 'province_id' => $province->id]);
        City::create(['name' => "خرامه ", 'province_id' => $province->id]);
        City::create(['name' => "خشت ", 'province_id' => $province->id]);
        City::create(['name' => "خنج ", 'province_id' => $province->id]);
        City::create(['name' => "خور ", 'province_id' => $province->id]);
        City::create(['name' => "خومه زار ", 'province_id' => $province->id]);
        City::create(['name' => "داراب ", 'province_id' => $province->id]);
        City::create(['name' => "داریان ", 'province_id' => $province->id]);
        City::create(['name' => "دبیران ", 'province_id' => $province->id]);
        City::create(['name' => "دژکرد ", 'province_id' => $province->id]);
        City::create(['name' => "دوبرجی ", 'province_id' => $province->id]);
        City::create(['name' => "دوزه ", 'province_id' => $province->id]);
        City::create(['name' => "دهرم ", 'province_id' => $province->id]);
        City::create(['name' => "رامجرد ", 'province_id' => $province->id]);
        City::create(['name' => "رونیز ", 'province_id' => $province->id]);
        City::create(['name' => "زاهدشهر ", 'province_id' => $province->id]);
        City::create(['name' => "زرقان ", 'province_id' => $province->id]);
        City::create(['name' => "سده ", 'province_id' => $province->id]);
        City::create(['name' => "سروستان ", 'province_id' => $province->id]);
        City::create(['name' => "سعادت شهر ", 'province_id' => $province->id]);
        City::create(['name' => "سورمق ", 'province_id' => $province->id]);
        City::create(['name' => "سیدان ", 'province_id' => $province->id]);
        City::create(['name' => "ششده ", 'province_id' => $province->id]);
        City::create(['name' => "شهر جدید صدرا ", 'province_id' => $province->id]);
        City::create(['name' => "شهرپیر ", 'province_id' => $province->id]);
        City::create(['name' => "شیراز ", 'province_id' => $province->id]);
        City::create(['name' => "صغاد ", 'province_id' => $province->id]);
        City::create(['name' => "صفاشهر ", 'province_id' => $province->id]);
        City::create(['name' => "علامرودشت ", 'province_id' => $province->id]);
        City::create(['name' => "عمادده ", 'province_id' => $province->id]);
        City::create(['name' => "فدامی ", 'province_id' => $province->id]);
        City::create(['name' => "فراشبند ", 'province_id' => $province->id]);
        City::create(['name' => "فسا ", 'province_id' => $province->id]);
        City::create(['name' => "فیروزآباد ", 'province_id' => $province->id]);
        City::create(['name' => "قادرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "قائمیه ", 'province_id' => $province->id]);
        City::create(['name' => "قطب آباد ", 'province_id' => $province->id]);
        City::create(['name' => "قطرویه ", 'province_id' => $province->id]);
        City::create(['name' => "قیر ", 'province_id' => $province->id]);
        City::create(['name' => "کارزین ", 'province_id' => $province->id]);
        City::create(['name' => "کازرون ", 'province_id' => $province->id]);
        City::create(['name' => "کامفیروز ", 'province_id' => $province->id]);
        City::create(['name' => "کره ای ", 'province_id' => $province->id]);
        City::create(['name' => "کنارتخته ", 'province_id' => $province->id]);
        City::create(['name' => "کوار ", 'province_id' => $province->id]);
        City::create(['name' => "کوهنجان ", 'province_id' => $province->id]);
        City::create(['name' => "گراش ", 'province_id' => $province->id]);
        City::create(['name' => "گله دار ", 'province_id' => $province->id]);
        City::create(['name' => "لار ", 'province_id' => $province->id]);
        City::create(['name' => "لامرد ", 'province_id' => $province->id]);
        City::create(['name' => "لپوئی ", 'province_id' => $province->id]);
        City::create(['name' => "لطیفی ", 'province_id' => $province->id]);
        City::create(['name' => "مبارک آباد ", 'province_id' => $province->id]);
        City::create(['name' => "مرودشت ", 'province_id' => $province->id]);
        City::create(['name' => "مشکان ", 'province_id' => $province->id]);
        City::create(['name' => "مصیری ", 'province_id' => $province->id]);
        City::create(['name' => "مهر ", 'province_id' => $province->id]);
        City::create(['name' => "میمند ", 'province_id' => $province->id]);
        City::create(['name' => "نوبندگان ", 'province_id' => $province->id]);
        City::create(['name' => "نوجین ", 'province_id' => $province->id]);
        City::create(['name' => "نودان ", 'province_id' => $province->id]);
        City::create(['name' => "نورآباد ", 'province_id' => $province->id]);
        City::create(['name' => "نی ریز ", 'province_id' => $province->id]);
        City::create(['name' => "وراوی ", 'province_id' => $province->id]);
        City::create(['name' => "هماشهر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'قزوین']);
        City::create(['name' => "ارداق ", 'province_id' => $province->id]);
        City::create(['name' => "اسفرورین ", 'province_id' => $province->id]);
        City::create(['name' => "اقبالیه ", 'province_id' => $province->id]);
        City::create(['name' => "الوند ", 'province_id' => $province->id]);
        City::create(['name' => "آبگرم ", 'province_id' => $province->id]);
        City::create(['name' => "آبیک ", 'province_id' => $province->id]);
        City::create(['name' => "آوج ", 'province_id' => $province->id]);
        City::create(['name' => "بوئین زهرا ", 'province_id' => $province->id]);
        City::create(['name' => "بیدستان ", 'province_id' => $province->id]);
        City::create(['name' => "تاکستان ", 'province_id' => $province->id]);
        City::create(['name' => "خاکعلی ", 'province_id' => $province->id]);
        City::create(['name' => "خرمدشت ", 'province_id' => $province->id]);
        City::create(['name' => "دانسفهان ", 'province_id' => $province->id]);
        City::create(['name' => "رازمیان ", 'province_id' => $province->id]);
        City::create(['name' => "سگزآباد ", 'province_id' => $province->id]);
        City::create(['name' => "سیردان ", 'province_id' => $province->id]);
        City::create(['name' => "شال ", 'province_id' => $province->id]);
        City::create(['name' => "شریفیه ", 'province_id' => $province->id]);
        City::create(['name' => "ضیاءآباد ", 'province_id' => $province->id]);
        City::create(['name' => "قزوین ", 'province_id' => $province->id]);
        City::create(['name' => "کوهین ", 'province_id' => $province->id]);
        City::create(['name' => "محمدیه ", 'province_id' => $province->id]);
        City::create(['name' => "محمودآبادنمونه ", 'province_id' => $province->id]);
        City::create(['name' => "معلم کلایه ", 'province_id' => $province->id]);
        City::create(['name' => "نرجه", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'قم']);
        City::create(['name' => "جعفریه ", 'province_id' => $province->id]);
        City::create(['name' => "دستجرد ", 'province_id' => $province->id]);
        City::create(['name' => "سلفچگان ", 'province_id' => $province->id]);
        City::create(['name' => "قم ", 'province_id' => $province->id]);
        City::create(['name' => "قنوات ", 'province_id' => $province->id]);
        City::create(['name' => "کهک", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'کردستان']);
        City::create(['name' => "آرمرده ", 'province_id' => $province->id]);
        City::create(['name' => "بابارشانی ", 'province_id' => $province->id]);
        City::create(['name' => "بانه ", 'province_id' => $province->id]);
        City::create(['name' => "بلبان آباد ", 'province_id' => $province->id]);
        City::create(['name' => "بوئین سفلی ", 'province_id' => $province->id]);
        City::create(['name' => "بیجار ", 'province_id' => $province->id]);
        City::create(['name' => "چناره ", 'province_id' => $province->id]);
        City::create(['name' => "دزج ", 'province_id' => $province->id]);
        City::create(['name' => "دلبران ", 'province_id' => $province->id]);
        City::create(['name' => "دهگلان ", 'province_id' => $province->id]);
        City::create(['name' => "دیواندره ", 'province_id' => $province->id]);
        City::create(['name' => "زرینه ", 'province_id' => $province->id]);
        City::create(['name' => "سروآباد ", 'province_id' => $province->id]);
        City::create(['name' => "سریش آباد ", 'province_id' => $province->id]);
        City::create(['name' => "سقز ", 'province_id' => $province->id]);
        City::create(['name' => "سنندج ", 'province_id' => $province->id]);
        City::create(['name' => "شویشه ", 'province_id' => $province->id]);
        City::create(['name' => "صاحب ", 'province_id' => $province->id]);
        City::create(['name' => "قروه ", 'province_id' => $province->id]);
        City::create(['name' => "کامیاران ", 'province_id' => $province->id]);
        City::create(['name' => "کانی دینار ", 'province_id' => $province->id]);
        City::create(['name' => "کانی سور ", 'province_id' => $province->id]);
        City::create(['name' => "مریوان ", 'province_id' => $province->id]);
        City::create(['name' => "موچش ", 'province_id' => $province->id]);
        City::create(['name' => "یاسوکند", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'کرمان']);
        City::create(['name' => "اختیارآباد ", 'province_id' => $province->id]);
        City::create(['name' => "ارزوئیه ", 'province_id' => $province->id]);
        City::create(['name' => "امین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "انار ", 'province_id' => $province->id]);
        City::create(['name' => "اندوهجرد ", 'province_id' => $province->id]);
        City::create(['name' => "باغین ", 'province_id' => $province->id]);
        City::create(['name' => "بافت ", 'province_id' => $province->id]);
        City::create(['name' => "بردسیر ", 'province_id' => $province->id]);
        City::create(['name' => "بروات ", 'province_id' => $province->id]);
        City::create(['name' => "بزنجان ", 'province_id' => $province->id]);
        City::create(['name' => "بم ", 'province_id' => $province->id]);
        City::create(['name' => "بهرمان ", 'province_id' => $province->id]);
        City::create(['name' => "پاریز ", 'province_id' => $province->id]);
        City::create(['name' => "جبالبارز ", 'province_id' => $province->id]);
        City::create(['name' => "جوپار ", 'province_id' => $province->id]);
        City::create(['name' => "جوزم ", 'province_id' => $province->id]);
        City::create(['name' => "جیرفت ", 'province_id' => $province->id]);
        City::create(['name' => "چترود ", 'province_id' => $province->id]);
        City::create(['name' => "خاتون آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خانوک ", 'province_id' => $province->id]);
        City::create(['name' => "خورسند ", 'province_id' => $province->id]);
        City::create(['name' => "درب بهشت ", 'province_id' => $province->id]);
        City::create(['name' => "دوساری ", 'province_id' => $province->id]);
        City::create(['name' => "دهج ", 'province_id' => $province->id]);
        City::create(['name' => "رابر ", 'province_id' => $province->id]);
        City::create(['name' => "راور ", 'province_id' => $province->id]);
        City::create(['name' => "راین ", 'province_id' => $province->id]);
        City::create(['name' => "رفسنجان ", 'province_id' => $province->id]);
        City::create(['name' => "رودبار ", 'province_id' => $province->id]);
        City::create(['name' => "ریحان شهر ", 'province_id' => $province->id]);
        City::create(['name' => "زرند ", 'province_id' => $province->id]);
        City::create(['name' => "زنگی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "زیدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "سرچشمه ", 'province_id' => $province->id]);
        City::create(['name' => "سیرجان ", 'province_id' => $province->id]);
        City::create(['name' => "شهداد ", 'province_id' => $province->id]);
        City::create(['name' => "شهربابک ", 'province_id' => $province->id]);
        City::create(['name' => "صفائیه ", 'province_id' => $province->id]);
        City::create(['name' => "عنبرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "فاریاب ", 'province_id' => $province->id]);
        City::create(['name' => "فهرج ", 'province_id' => $province->id]);
        City::create(['name' => "قلعه گنج ", 'province_id' => $province->id]);
        City::create(['name' => "کاظم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "کرمان ", 'province_id' => $province->id]);
        City::create(['name' => "کشکوئیه ", 'province_id' => $province->id]);
        City::create(['name' => "کوهبنان ", 'province_id' => $province->id]);
        City::create(['name' => "کهنوج ", 'province_id' => $province->id]);
        City::create(['name' => "کیانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "گلباف ", 'province_id' => $province->id]);
        City::create(['name' => "گلزار ", 'province_id' => $province->id]);
        City::create(['name' => "لاله زار ", 'province_id' => $province->id]);
        City::create(['name' => "ماهان ", 'province_id' => $province->id]);
        City::create(['name' => "محمد آباد ", 'province_id' => $province->id]);
        City::create(['name' => "محی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "مردهک ", 'province_id' => $province->id]);
        City::create(['name' => "منوجان ", 'province_id' => $province->id]);
        City::create(['name' => "نجف شهر ", 'province_id' => $province->id]);
        City::create(['name' => "نرماشیر ", 'province_id' => $province->id]);
        City::create(['name' => "نظام شهر ", 'province_id' => $province->id]);
        City::create(['name' => "نگار ", 'province_id' => $province->id]);
        City::create(['name' => "نودژ ", 'province_id' => $province->id]);
        City::create(['name' => "هجدک ", 'province_id' => $province->id]);
        City::create(['name' => "هماشهر ", 'province_id' => $province->id]);
        City::create(['name' => "یزدان شهر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'کرمانشاه']);
        City::create(['name' => "ازگله ", 'province_id' => $province->id]);
        City::create(['name' => "اسلام آبادغرب ", 'province_id' => $province->id]);
        City::create(['name' => "باینگان ", 'province_id' => $province->id]);
        City::create(['name' => "بیستون ", 'province_id' => $province->id]);
        City::create(['name' => "پاوه ", 'province_id' => $province->id]);
        City::create(['name' => "تازه آباد ", 'province_id' => $province->id]);
        City::create(['name' => "جوانرود ", 'province_id' => $province->id]);
        City::create(['name' => "حمیل ", 'province_id' => $province->id]);
        City::create(['name' => "رباط ", 'province_id' => $province->id]);
        City::create(['name' => "روانسر ", 'province_id' => $province->id]);
        City::create(['name' => "سرپل ذهاب ", 'province_id' => $province->id]);
        City::create(['name' => "سرمست ", 'province_id' => $province->id]);
        City::create(['name' => "سطر ", 'province_id' => $province->id]);
        City::create(['name' => "سنقر ", 'province_id' => $province->id]);
        City::create(['name' => "سومار ", 'province_id' => $province->id]);
        City::create(['name' => "شاهو ", 'province_id' => $province->id]);
        City::create(['name' => "صحنه ", 'province_id' => $province->id]);
        City::create(['name' => "قصرشیرین ", 'province_id' => $province->id]);
        City::create(['name' => "کرمانشاه ", 'province_id' => $province->id]);
        City::create(['name' => "کرندغرب ", 'province_id' => $province->id]);
        City::create(['name' => "کنگاور ", 'province_id' => $province->id]);
        City::create(['name' => "کوزران ", 'province_id' => $province->id]);
        City::create(['name' => "گهواره ", 'province_id' => $province->id]);
        City::create(['name' => "گیلانغرب ", 'province_id' => $province->id]);
        City::create(['name' => "میان راهان ", 'province_id' => $province->id]);
        City::create(['name' => "نودشه ", 'province_id' => $province->id]);
        City::create(['name' => "نوسود ", 'province_id' => $province->id]);
        City::create(['name' => "هرسین ", 'province_id' => $province->id]);
        City::create(['name' => "هلشی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'کهگیلویه وبویراحمد']);
        City::create(['name' => "باشت ", 'province_id' => $province->id]);
        City::create(['name' => "پاتاوه ", 'province_id' => $province->id]);
        City::create(['name' => "چرام ", 'province_id' => $province->id]);
        City::create(['name' => "چیتاب ", 'province_id' => $province->id]);
        City::create(['name' => "دوگنبدان ", 'province_id' => $province->id]);
        City::create(['name' => "دهدشت ", 'province_id' => $province->id]);
        City::create(['name' => "دیشموک ", 'province_id' => $province->id]);
        City::create(['name' => "سوق ", 'province_id' => $province->id]);
        City::create(['name' => "سی سخت ", 'province_id' => $province->id]);
        City::create(['name' => "قلعه رئیسی ", 'province_id' => $province->id]);
        City::create(['name' => "گراب سفلی ", 'province_id' => $province->id]);
        City::create(['name' => "لنده ", 'province_id' => $province->id]);
        City::create(['name' => "لیکک ", 'province_id' => $province->id]);
        City::create(['name' => "مادوان ", 'province_id' => $province->id]);
        City::create(['name' => "مارگون ", 'province_id' => $province->id]);
        City::create(['name' => "یاسوج", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'گلستان']);
        City::create(['name' => "انبارآلوم ", 'province_id' => $province->id]);
        City::create(['name' => "اینچه برون ", 'province_id' => $province->id]);
        City::create(['name' => "آزادشهر ", 'province_id' => $province->id]);
        City::create(['name' => "آق قلا ", 'province_id' => $province->id]);
        City::create(['name' => "بندرگز ", 'province_id' => $province->id]);
        City::create(['name' => "ترکمن ", 'province_id' => $province->id]);
        City::create(['name' => "جلین ", 'province_id' => $province->id]);
        City::create(['name' => "خان ببین ", 'province_id' => $province->id]);
        City::create(['name' => "دلند ", 'province_id' => $province->id]);
        City::create(['name' => "رامیان ", 'province_id' => $province->id]);
        City::create(['name' => "سرخنکلاته ", 'province_id' => $province->id]);
        City::create(['name' => "سیمین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "علی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فاضل آباد ", 'province_id' => $province->id]);
        City::create(['name' => "کردکوی ", 'province_id' => $province->id]);
        City::create(['name' => "کلاله ", 'province_id' => $province->id]);
        City::create(['name' => "گالیکش ", 'province_id' => $province->id]);
        City::create(['name' => "گرگان ", 'province_id' => $province->id]);
        City::create(['name' => "گمیش تپه ", 'province_id' => $province->id]);
        City::create(['name' => "گنبد کاووس ", 'province_id' => $province->id]);
        City::create(['name' => "مراوه تپه ", 'province_id' => $province->id]);
        City::create(['name' => "مینودشت ", 'province_id' => $province->id]);
        City::create(['name' => "نگین شهر ", 'province_id' => $province->id]);
        City::create(['name' => "نوده خاندوز ", 'province_id' => $province->id]);
        City::create(['name' => "نوکنده", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'گیلان']);
        City::create(['name' => "احمدسرگوراب ", 'province_id' => $province->id]);
        City::create(['name' => "اسالم ", 'province_id' => $province->id]);
        City::create(['name' => "اطاقور ", 'province_id' => $province->id]);
        City::create(['name' => "املش ", 'province_id' => $province->id]);
        City::create(['name' => "آستارا ", 'province_id' => $province->id]);
        City::create(['name' => "آستانه اشرفیه ", 'province_id' => $province->id]);
        City::create(['name' => "بازارجمعه ", 'province_id' => $province->id]);
        City::create(['name' => "بره سر ", 'province_id' => $province->id]);
        City::create(['name' => "بندرانزلی ", 'province_id' => $province->id]);
        City::create(['name' => "پره سر ", 'province_id' => $province->id]);
        City::create(['name' => "توتکابن ", 'province_id' => $province->id]);
        City::create(['name' => "جیرنده ", 'province_id' => $province->id]);
        City::create(['name' => "چابکسر ", 'province_id' => $province->id]);
        City::create(['name' => "چاف وچمخاله ", 'province_id' => $province->id]);
        City::create(['name' => "چوبر ", 'province_id' => $province->id]);
        City::create(['name' => "حویق ", 'province_id' => $province->id]);
        City::create(['name' => "خشکبیجار ", 'province_id' => $province->id]);
        City::create(['name' => "خمام ", 'province_id' => $province->id]);
        City::create(['name' => "دیلمان ", 'province_id' => $province->id]);
        City::create(['name' => "رانکوه ", 'province_id' => $province->id]);
        City::create(['name' => "رحیم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "رستم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "رشت ", 'province_id' => $province->id]);
        City::create(['name' => "رضوانشهر ", 'province_id' => $province->id]);
        City::create(['name' => "رودبار ", 'province_id' => $province->id]);
        City::create(['name' => "رودبنه ", 'province_id' => $province->id]);
        City::create(['name' => "رودسر ", 'province_id' => $province->id]);
        City::create(['name' => "سنگر ", 'province_id' => $province->id]);
        City::create(['name' => "سیاهکل ", 'province_id' => $province->id]);
        City::create(['name' => "شفت ", 'province_id' => $province->id]);
        City::create(['name' => "شلمان ", 'province_id' => $province->id]);
        City::create(['name' => "صومعه سرا ", 'province_id' => $province->id]);
        City::create(['name' => "فومن ", 'province_id' => $province->id]);
        City::create(['name' => "کلاچای ", 'province_id' => $province->id]);
        City::create(['name' => "کوچصفهان ", 'province_id' => $province->id]);
        City::create(['name' => "کومله ", 'province_id' => $province->id]);
        City::create(['name' => "کیاشهر ", 'province_id' => $province->id]);
        City::create(['name' => "گوراب زرمیخ ", 'province_id' => $province->id]);
        City::create(['name' => "لاهیجان ", 'province_id' => $province->id]);
        City::create(['name' => "لشت نشاء ", 'province_id' => $province->id]);
        City::create(['name' => "لنگرود ", 'province_id' => $province->id]);
        City::create(['name' => "لوشان ", 'province_id' => $province->id]);
        City::create(['name' => "لولمان ", 'province_id' => $province->id]);
        City::create(['name' => "لوندویل ", 'province_id' => $province->id]);
        City::create(['name' => "لیسار ", 'province_id' => $province->id]);
        City::create(['name' => "ماسال ", 'province_id' => $province->id]);
        City::create(['name' => "ماسوله ", 'province_id' => $province->id]);
        City::create(['name' => "مرجقل ", 'province_id' => $province->id]);
        City::create(['name' => "منجیل ", 'province_id' => $province->id]);
        City::create(['name' => "واجارگاه ", 'province_id' => $province->id]);
        City::create(['name' => "هشتپر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'لرستان']);
        City::create(['name' => "ازنا ", 'province_id' => $province->id]);
        City::create(['name' => "اشترینان ", 'province_id' => $province->id]);
        City::create(['name' => "الشتر ", 'province_id' => $province->id]);
        City::create(['name' => "الیگودرز ", 'province_id' => $province->id]);
        City::create(['name' => "بروجرد ", 'province_id' => $province->id]);
        City::create(['name' => "پلدختر ", 'province_id' => $province->id]);
        City::create(['name' => "چالانچولان ", 'province_id' => $province->id]);
        City::create(['name' => "چغلوندی ", 'province_id' => $province->id]);
        City::create(['name' => "چقابل ", 'province_id' => $province->id]);
        City::create(['name' => "خرم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "درب گنبد ", 'province_id' => $province->id]);
        City::create(['name' => "دورود ", 'province_id' => $province->id]);
        City::create(['name' => "زاغه ", 'province_id' => $province->id]);
        City::create(['name' => "سپیددشت ", 'province_id' => $province->id]);
        City::create(['name' => "سراب دوره ", 'province_id' => $province->id]);
        City::create(['name' => "شول آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فیروز آباد ", 'province_id' => $province->id]);
        City::create(['name' => "کونانی ", 'province_id' => $province->id]);
        City::create(['name' => "کوهدشت ", 'province_id' => $province->id]);
        City::create(['name' => "گراب ", 'province_id' => $province->id]);
        City::create(['name' => "معمولان ", 'province_id' => $province->id]);
        City::create(['name' => "مؤمن آباد ", 'province_id' => $province->id]);
        City::create(['name' => "نور آباد ", 'province_id' => $province->id]);
        City::create(['name' => "ویسیان ", 'province_id' => $province->id]);
        City::create(['name' => "هفت چشمه", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'مازندران']);
        City::create(['name' => "امیرکلا ", 'province_id' => $province->id]);
        City::create(['name' => "ایزدشهر ", 'province_id' => $province->id]);
        City::create(['name' => "آلاشت ", 'province_id' => $province->id]);
        City::create(['name' => "آمل ", 'province_id' => $province->id]);
        City::create(['name' => "بابل ", 'province_id' => $province->id]);
        City::create(['name' => "بابلسر ", 'province_id' => $province->id]);
        City::create(['name' => "بلده ", 'province_id' => $province->id]);
        City::create(['name' => "بهشهر ", 'province_id' => $province->id]);
        City::create(['name' => "بهنمیر ", 'province_id' => $province->id]);
        City::create(['name' => "پل سفید ", 'province_id' => $province->id]);
        City::create(['name' => "پول ", 'province_id' => $province->id]);
        City::create(['name' => "تنکابن ", 'province_id' => $province->id]);
        City::create(['name' => "جویبار ", 'province_id' => $province->id]);
        City::create(['name' => "چالوس ", 'province_id' => $province->id]);
        City::create(['name' => "چمستان ", 'province_id' => $province->id]);
        City::create(['name' => "خرم آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خلیل شهر ", 'province_id' => $province->id]);
        City::create(['name' => "خوش رودپی ", 'province_id' => $province->id]);
        City::create(['name' => "دابودشت ", 'province_id' => $province->id]);
        City::create(['name' => "رامسر ", 'province_id' => $province->id]);
        City::create(['name' => "رستمکلا ", 'province_id' => $province->id]);
        City::create(['name' => "رویان ", 'province_id' => $province->id]);
        City::create(['name' => "رینه ", 'province_id' => $province->id]);
        City::create(['name' => "زرگر محله ", 'province_id' => $province->id]);
        City::create(['name' => "زیرآب ", 'province_id' => $province->id]);
        City::create(['name' => "ساری ", 'province_id' => $province->id]);
        City::create(['name' => "سرخرود ", 'province_id' => $province->id]);
        City::create(['name' => "سلمان شهر ", 'province_id' => $province->id]);
        City::create(['name' => "سورک ", 'province_id' => $province->id]);
        City::create(['name' => "شیرگاه ", 'province_id' => $province->id]);
        City::create(['name' => "شیرود ", 'province_id' => $province->id]);
        City::create(['name' => "عباس آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فریدونکنار ", 'province_id' => $province->id]);
        City::create(['name' => "فریم ", 'province_id' => $province->id]);
        City::create(['name' => "قائم شهر ", 'province_id' => $province->id]);
        City::create(['name' => "کتالم وسادات شهر ", 'province_id' => $province->id]);
        City::create(['name' => "کلارآباد ", 'province_id' => $province->id]);
        City::create(['name' => "کلاردشت ", 'province_id' => $province->id]);
        City::create(['name' => "کله بست ", 'province_id' => $province->id]);
        City::create(['name' => "کوهی خیل ", 'province_id' => $province->id]);
        City::create(['name' => "کیاسر ", 'province_id' => $province->id]);
        City::create(['name' => "کیاکلا ", 'province_id' => $province->id]);
        City::create(['name' => "گتاب ", 'province_id' => $province->id]);
        City::create(['name' => "گزنک ", 'province_id' => $province->id]);
        City::create(['name' => "گلوگاه ", 'province_id' => $province->id]);
        City::create(['name' => "محمود آباد ", 'province_id' => $province->id]);
        City::create(['name' => "مرزن آباد ", 'province_id' => $province->id]);
        City::create(['name' => "مرزیکلا ", 'province_id' => $province->id]);
        City::create(['name' => "نشتارود ", 'province_id' => $province->id]);
        City::create(['name' => "نکا ", 'province_id' => $province->id]);
        City::create(['name' => "نور ", 'province_id' => $province->id]);
        City::create(['name' => "نوشهر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'مرکزی']);
        City::create(['name' => "اراک ", 'province_id' => $province->id]);
        City::create(['name' => "آستانه ", 'province_id' => $province->id]);
        City::create(['name' => "آشتیان ", 'province_id' => $province->id]);
        City::create(['name' => "پرندک ", 'province_id' => $province->id]);
        City::create(['name' => "تفرش ", 'province_id' => $province->id]);
        City::create(['name' => "توره ", 'province_id' => $province->id]);
        City::create(['name' => "جاورسیان ", 'province_id' => $province->id]);
        City::create(['name' => "خشکرود ", 'province_id' => $province->id]);
        City::create(['name' => "خمین ", 'province_id' => $province->id]);
        City::create(['name' => "خنداب ", 'province_id' => $province->id]);
        City::create(['name' => "داودآباد ", 'province_id' => $province->id]);
        City::create(['name' => "دلیجان ", 'province_id' => $province->id]);
        City::create(['name' => "رازقان ", 'province_id' => $province->id]);
        City::create(['name' => "زاویه ", 'province_id' => $province->id]);
        City::create(['name' => "ساروق ", 'province_id' => $province->id]);
        City::create(['name' => "ساوه ", 'province_id' => $province->id]);
        City::create(['name' => "سنجان ", 'province_id' => $province->id]);
        City::create(['name' => "شازند ", 'province_id' => $province->id]);
        City::create(['name' => "شهرجدیدمهاجران ", 'province_id' => $province->id]);
        City::create(['name' => "غرق آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فرمهین ", 'province_id' => $province->id]);
        City::create(['name' => "قورچی باشی ", 'province_id' => $province->id]);
        City::create(['name' => "کرهرود ", 'province_id' => $province->id]);
        City::create(['name' => "کمیجان ", 'province_id' => $province->id]);
        City::create(['name' => "مأمونیه ", 'province_id' => $province->id]);
        City::create(['name' => "محلات ", 'province_id' => $province->id]);
        City::create(['name' => "میلاجرد ", 'province_id' => $province->id]);
        City::create(['name' => "نراق ", 'province_id' => $province->id]);
        City::create(['name' => "نوبران ", 'province_id' => $province->id]);
        City::create(['name' => "نیمور ", 'province_id' => $province->id]);
        City::create(['name' => "هندودر", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'هرمزگان']);
        City::create(['name' => "ابوموسی ", 'province_id' => $province->id]);
        City::create(['name' => "بستک ", 'province_id' => $province->id]);
        City::create(['name' => "بندرجاسک ", 'province_id' => $province->id]);
        City::create(['name' => "بندرچارک ", 'province_id' => $province->id]);
        City::create(['name' => "بندرعباس ", 'province_id' => $province->id]);
        City::create(['name' => "بندرلنگه ", 'province_id' => $province->id]);
        City::create(['name' => "بیکاه ", 'province_id' => $province->id]);
        City::create(['name' => "پارسیان ", 'province_id' => $province->id]);
        City::create(['name' => "تخت ", 'province_id' => $province->id]);
        City::create(['name' => "جناح ", 'province_id' => $province->id]);
        City::create(['name' => "حاجی آباد ", 'province_id' => $province->id]);
        City::create(['name' => "خمیر ", 'province_id' => $province->id]);
        City::create(['name' => "درگهان ", 'province_id' => $province->id]);
        City::create(['name' => "دهبارز ", 'province_id' => $province->id]);
        City::create(['name' => "رویدر ", 'province_id' => $province->id]);
        City::create(['name' => "زیارتعلی ", 'province_id' => $province->id]);
        City::create(['name' => "سردشت بشاگرد ", 'province_id' => $province->id]);
        City::create(['name' => "سرگز ", 'province_id' => $province->id]);
        City::create(['name' => "سندرک ", 'province_id' => $province->id]);
        City::create(['name' => "سوزا ", 'province_id' => $province->id]);
        City::create(['name' => "سیریک ", 'province_id' => $province->id]);
        City::create(['name' => "فارغان ", 'province_id' => $province->id]);
        City::create(['name' => "فین ", 'province_id' => $province->id]);
        City::create(['name' => "قشم ", 'province_id' => $province->id]);
        City::create(['name' => "قلعه قاضی ", 'province_id' => $province->id]);
        City::create(['name' => "کنگ ", 'province_id' => $province->id]);
        City::create(['name' => "کوشکنار ", 'province_id' => $province->id]);
        City::create(['name' => "کیش ", 'province_id' => $province->id]);
        City::create(['name' => "گوهران ", 'province_id' => $province->id]);
        City::create(['name' => "میناب ", 'province_id' => $province->id]);
        City::create(['name' => "هرمز ", 'province_id' => $province->id]);
        City::create(['name' => "هشتبندی", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'همدان']);
        City::create(['name' => "ازندریان ", 'province_id' => $province->id]);
        City::create(['name' => "اسدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "برزول ", 'province_id' => $province->id]);
        City::create(['name' => "بهار ", 'province_id' => $province->id]);
        City::create(['name' => "تویسرکان ", 'province_id' => $province->id]);
        City::create(['name' => "جورقان ", 'province_id' => $province->id]);
        City::create(['name' => "جوکار ", 'province_id' => $province->id]);
        City::create(['name' => "دمق ", 'province_id' => $province->id]);
        City::create(['name' => "رزن ", 'province_id' => $province->id]);
        City::create(['name' => "زنگنه ", 'province_id' => $province->id]);
        City::create(['name' => "سامن ", 'province_id' => $province->id]);
        City::create(['name' => "سرکان ", 'province_id' => $province->id]);
        City::create(['name' => "شیرین سو ", 'province_id' => $province->id]);
        City::create(['name' => "صالح آباد ", 'province_id' => $province->id]);
        City::create(['name' => "فامنین ", 'province_id' => $province->id]);
        City::create(['name' => "فرسفج ", 'province_id' => $province->id]);
        City::create(['name' => "فیروزان ", 'province_id' => $province->id]);
        City::create(['name' => "قروه در جزین ", 'province_id' => $province->id]);
        City::create(['name' => "قهاوند ", 'province_id' => $province->id]);
        City::create(['name' => "کبودرآهنگ ", 'province_id' => $province->id]);
        City::create(['name' => "گل تپه ", 'province_id' => $province->id]);
        City::create(['name' => "گیان ", 'province_id' => $province->id]);
        City::create(['name' => "لالجین ", 'province_id' => $province->id]);
        City::create(['name' => "مریانج ", 'province_id' => $province->id]);
        City::create(['name' => "ملایر ", 'province_id' => $province->id]);
        City::create(['name' => "نهاوند ", 'province_id' => $province->id]);
        City::create(['name' => "همدان", 'province_id' => $province->id]);

        $province = Province::create(['name' => 'یزد']);
        City::create(['name' => "ابرکوه ", 'province_id' => $province->id]);
        City::create(['name' => "احمدآباد ", 'province_id' => $province->id]);
        City::create(['name' => "اردکان ", 'province_id' => $province->id]);
        City::create(['name' => "اشکذر ", 'province_id' => $province->id]);
        City::create(['name' => "بافق ", 'province_id' => $province->id]);
        City::create(['name' => "بفروئیه ", 'province_id' => $province->id]);
        City::create(['name' => "بهاباد ", 'province_id' => $province->id]);
        City::create(['name' => "تفت ", 'province_id' => $province->id]);
        City::create(['name' => "حمیدیا ", 'province_id' => $province->id]);
        City::create(['name' => "خضرآباد ", 'province_id' => $province->id]);
        City::create(['name' => "دیهوک ", 'province_id' => $province->id]);
        City::create(['name' => "زارچ ", 'province_id' => $province->id]);
        City::create(['name' => "شاهدیه ", 'province_id' => $province->id]);
        City::create(['name' => "طبس ", 'province_id' => $province->id]);
        City::create(['name' => "عشق آباد ", 'province_id' => $province->id]);
        City::create(['name' => "عقدا ", 'province_id' => $province->id]);
        City::create(['name' => "مروست ", 'province_id' => $province->id]);
        City::create(['name' => "مهردشت ", 'province_id' => $province->id]);
        City::create(['name' => "مهریز ", 'province_id' => $province->id]);
        City::create(['name' => "میبد ", 'province_id' => $province->id]);
        City::create(['name' => "ندوشن ", 'province_id' => $province->id]);
        City::create(['name' => "نیر ", 'province_id' => $province->id]);
        City::create(['name' => "هرات ", 'province_id' => $province->id]);
        City::create(['name' => "یزد", 'province_id' => $province->id]);

    }
}
