<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvincesAndCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $province = Province::create(['name' => 'آذربایجان شرقی']);
        City::create(['name' => 'تبریز', 'province_id' => $province->id]);
        City::create(['name' => 'مراغه', 'province_id' => $province->id]);
        City::create(['name' => 'مرند', 'province_id' => $province->id]);
        City::create(['name' => 'آذرشهر', 'province_id' => $province->id]);
        City::create(['name' => 'بناب', 'province_id' => $province->id]);
        City::create(['name' => 'میانه', 'province_id' => $province->id]);
        City::create(['name' => 'اهر', 'province_id' => $province->id]);
        City::create(['name' => 'شبستر', 'province_id' => $province->id]);
        City::create(['name' => 'سراب', 'province_id' => $province->id]);
        City::create(['name' => 'ملکان', 'province_id' => $province->id]);
        City::create(['name' => 'هریس', 'province_id' => $province->id]);
        City::create(['name' => 'هشترود', 'province_id' => $province->id]);
        City::create(['name' => 'جلفا', 'province_id' => $province->id]);
        City::create(['name' => 'ورزقان', 'province_id' => $province->id]);
        City::create(['name' => 'چاراویماق', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'آذربایجان غربی']);
        City::create(['name' => 'ارومیه', 'province_id' => $province->id]);
        City::create(['name' => 'خوی', 'province_id' => $province->id]);
        City::create(['name' => 'بوکان', 'province_id' => $province->id]);
        City::create(['name' => 'مهاباد', 'province_id' => $province->id]);
        City::create(['name' => 'میاندوآب', 'province_id' => $province->id]);
        City::create(['name' => 'سلماس', 'province_id' => $province->id]);
        City::create(['name' => 'پیرانشهر', 'province_id' => $province->id]);
        City::create(['name' => 'نقده', 'province_id' => $province->id]);
        City::create(['name' => 'سردشت', 'province_id' => $province->id]);
        City::create(['name' => 'تکاب', 'province_id' => $province->id]);
        City::create(['name' => 'شاهین‌دژ', 'province_id' => $province->id]);
        City::create(['name' => 'چالدران', 'province_id' => $province->id]);
        City::create(['name' => 'اشنویه', 'province_id' => $province->id]);
        City::create(['name' => 'شوط', 'province_id' => $province->id]);
        City::create(['name' => 'پلدشت', 'province_id' => $province->id]);
        City::create(['name' => 'چایپاره', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'اردبیل']);
        City::create(['name' => 'اردبیل', 'province_id' => $province->id]);
        City::create(['name' => 'پارس‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'مشگین‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'گرمی', 'province_id' => $province->id]);
        City::create(['name' => 'خلخال', 'province_id' => $province->id]);
        City::create(['name' => 'بیله‌سوار', 'province_id' => $province->id]);
        City::create(['name' => 'نمین', 'province_id' => $province->id]);
        City::create(['name' => 'نیر', 'province_id' => $province->id]);
        City::create(['name' => 'کوثر', 'province_id' => $province->id]);
        City::create(['name' => 'سرعین', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'اصفهان']);
        City::create(['name' => 'اصفهان', 'province_id' => $province->id]);
        City::create(['name' => 'کاشان', 'province_id' => $province->id]);
        City::create(['name' => 'خمینی‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'نجف‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'لنجان', 'province_id' => $province->id]);
        City::create(['name' => 'شاهین‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'فلاورجان', 'province_id' => $province->id]);
        City::create(['name' => 'شهرضا', 'province_id' => $province->id]);
        City::create(['name' => 'نایین', 'province_id' => $province->id]);
        City::create(['name' => 'مبارکه', 'province_id' => $province->id]);
        City::create(['name' => 'آران و بیدگل', 'province_id' => $province->id]);
        City::create(['name' => 'فریدن', 'province_id' => $province->id]);
        City::create(['name' => 'سمیرم', 'province_id' => $province->id]);
        City::create(['name' => 'گلپایگان', 'province_id' => $province->id]);
        City::create(['name' => 'خوانسار', 'province_id' => $province->id]);
        City::create(['name' => 'برخوار', 'province_id' => $province->id]);
        City::create(['name' => 'دهاقان', 'province_id' => $province->id]);
        City::create(['name' => 'تیران و کرون', 'province_id' => $province->id]);
        City::create(['name' => 'چادگان', 'province_id' => $province->id]);
        City::create(['name' => 'فریدون‌شهر', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'البرز']);
        City::create(['name' => 'کرج', 'province_id' => $province->id]);
        City::create(['name' => 'نظرآباد', 'province_id' => $province->id]);
        City::create(['name' => 'طالقان', 'province_id' => $province->id]);
        City::create(['name' => 'ساوجبلاغ', 'province_id' => $province->id]);
        City::create(['name' => 'اشتهارد', 'province_id' => $province->id]);
        City::create(['name' => 'فردیس', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'ایلام']);
        City::create(['name' => 'ایلام', 'province_id' => $province->id]);
        City::create(['name' => 'دهلران', 'province_id' => $province->id]);
        City::create(['name' => 'دره‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'آبدانان', 'province_id' => $province->id]);
        City::create(['name' => 'ملکشاهی', 'province_id' => $province->id]);
        City::create(['name' => 'چرداول', 'province_id' => $province->id]);
        City::create(['name' => 'ایوان', 'province_id' => $province->id]);
        City::create(['name' => 'بدره', 'province_id' => $province->id]);
        City::create(['name' => 'مهران', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'بوشهر']);
        City::create(['name' => 'بوشهر', 'province_id' => $province->id]);
        City::create(['name' => 'دشتستان', 'province_id' => $province->id]);
        City::create(['name' => 'دشتی', 'province_id' => $province->id]);
        City::create(['name' => 'تنگستان', 'province_id' => $province->id]);
        City::create(['name' => 'گناوه', 'province_id' => $province->id]);
        City::create(['name' => 'کنگان', 'province_id' => $province->id]);
        City::create(['name' => 'جم', 'province_id' => $province->id]);
        City::create(['name' => 'عسلویه', 'province_id' => $province->id]);
        City::create(['name' => 'دیلم', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'تهران']);
        City::create(['name' => 'تهران', 'province_id' => $province->id]);
        City::create(['name' => 'ری', 'province_id' => $province->id]);
        City::create(['name' => 'شمیرانات', 'province_id' => $province->id]);
        City::create(['name' => 'اسلامشهر', 'province_id' => $province->id]);
        City::create(['name' => 'پردیس', 'province_id' => $province->id]);
        City::create(['name' => 'دماوند', 'province_id' => $province->id]);
        City::create(['name' => 'ورامین', 'province_id' => $province->id]);
        City::create(['name' => 'پاکدشت', 'province_id' => $province->id]);
        City::create(['name' => 'قرچک', 'province_id' => $province->id]);
        City::create(['name' => 'بهارستان', 'province_id' => $province->id]);
        City::create(['name' => 'رباط‌کریم', 'province_id' => $province->id]);
        City::create(['name' => 'ملارد', 'province_id' => $province->id]);
        City::create(['name' => 'شهریار', 'province_id' => $province->id]);
        City::create(['name' => 'قدس', 'province_id' => $province->id]);
        City::create(['name' => 'فیروزکوه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'چهارمحال و بختیاری']);
        City::create(['name' => 'شهرکرد', 'province_id' => $province->id]);
        City::create(['name' => 'بروجن', 'province_id' => $province->id]);
        City::create(['name' => 'فارسان', 'province_id' => $province->id]);
        City::create(['name' => 'کوهرنگ', 'province_id' => $province->id]);
        City::create(['name' => 'اردل', 'province_id' => $province->id]);
        City::create(['name' => 'لردگان', 'province_id' => $province->id]);
        City::create(['name' => 'کیار', 'province_id' => $province->id]);
        City::create(['name' => 'سامان', 'province_id' => $province->id]);
        City::create(['name' => 'بن', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'خراسان جنوبی']);
        City::create(['name' => 'بیرجند', 'province_id' => $province->id]);
        City::create(['name' => 'قائن', 'province_id' => $province->id]);
        City::create(['name' => 'نهبندان', 'province_id' => $province->id]);
        City::create(['name' => 'فردوس', 'province_id' => $province->id]);
        City::create(['name' => 'طبس', 'province_id' => $province->id]);
        City::create(['name' => 'سرایان', 'province_id' => $province->id]);
        City::create(['name' => 'سربیشه', 'province_id' => $province->id]);
        City::create(['name' => 'درمیان', 'province_id' => $province->id]);
        City::create(['name' => 'بشرویه', 'province_id' => $province->id]);
        City::create(['name' => 'خوسف', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'خراسان رضوی']);
        City::create(['name' => 'مشهد', 'province_id' => $province->id]);
        City::create(['name' => 'نیشابور', 'province_id' => $province->id]);
        City::create(['name' => 'سبزوار', 'province_id' => $province->id]);
        City::create(['name' => 'تربت‌حیدریه', 'province_id' => $province->id]);
        City::create(['name' => 'قوچان', 'province_id' => $province->id]);
        City::create(['name' => 'کاشمر', 'province_id' => $province->id]);
        City::create(['name' => 'چناران', 'province_id' => $province->id]);
        City::create(['name' => 'تایباد', 'province_id' => $province->id]);
        City::create(['name' => 'خواف', 'province_id' => $province->id]);
        City::create(['name' => 'تربت‌جام', 'province_id' => $province->id]);
        City::create(['name' => 'سرخس', 'province_id' => $province->id]);
        City::create(['name' => 'درگز', 'province_id' => $province->id]);
        City::create(['name' => 'گناباد', 'province_id' => $province->id]);
        City::create(['name' => 'بردسکن', 'province_id' => $province->id]);
        City::create(['name' => 'فریمان', 'province_id' => $province->id]);
        City::create(['name' => 'طرقبه', 'province_id' => $province->id]);
        City::create(['name' => 'رشتخوار', 'province_id' => $province->id]);
        City::create(['name' => 'بینالود', 'province_id' => $province->id]);
        City::create(['name' => 'باخرز', 'province_id' => $province->id]);
        City::create(['name' => 'زاوه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'خراسان شمالی']);
        City::create(['name' => 'بجنورد', 'province_id' => $province->id]);
        City::create(['name' => 'شیروان', 'province_id' => $province->id]);
        City::create(['name' => 'اسفراین', 'province_id' => $province->id]);
        City::create(['name' => 'جاجرم', 'province_id' => $province->id]);
        City::create(['name' => 'مانه و سملقان', 'province_id' => $province->id]);
        City::create(['name' => 'گرمه', 'province_id' => $province->id]);
        City::create(['name' => 'فاروج', 'province_id' => $province->id]);
        City::create(['name' => 'راز و جرگلان', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'خوزستان']);
        City::create(['name' => 'اهواز', 'province_id' => $province->id]);
        City::create(['name' => 'آبادان', 'province_id' => $province->id]);
        City::create(['name' => 'دزفول', 'province_id' => $province->id]);
        City::create(['name' => 'خرمشهر', 'province_id' => $province->id]);
        City::create(['name' => 'شوش', 'province_id' => $province->id]);
        City::create(['name' => 'شادگان', 'province_id' => $province->id]);
        City::create(['name' => 'ماهشهر', 'province_id' => $province->id]);
        City::create(['name' => 'اندیمشک', 'province_id' => $province->id]);
        City::create(['name' => 'بهبهان', 'province_id' => $province->id]);
        City::create(['name' => 'مسجدسلیمان', 'province_id' => $province->id]);
        City::create(['name' => 'ایذه', 'province_id' => $province->id]);
        City::create(['name' => 'هندیجان', 'province_id' => $province->id]);
        City::create(['name' => 'رامهرمز', 'province_id' => $province->id]);
        City::create(['name' => 'رامشیر', 'province_id' => $province->id]);
        City::create(['name' => 'باغ‌ملک', 'province_id' => $province->id]);
        City::create(['name' => 'سوسنگرد', 'province_id' => $province->id]);
        City::create(['name' => 'امیدیه', 'province_id' => $province->id]);
        City::create(['name' => 'لالی', 'province_id' => $province->id]);
        City::create(['name' => 'شوشتر', 'province_id' => $province->id]);
        City::create(['name' => 'هفتکل', 'province_id' => $province->id]);
        City::create(['name' => 'باوی', 'province_id' => $province->id]);
        City::create(['name' => 'کارون', 'province_id' => $province->id]);
        City::create(['name' => 'حمیدیه', 'province_id' => $province->id]);
        City::create(['name' => 'اندیکا', 'province_id' => $province->id]);
        City::create(['name' => 'گتوند', 'province_id' => $province->id]);
        City::create(['name' => 'هویزه', 'province_id' => $province->id]);
        City::create(['name' => 'آغاجاری', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'زنجان']);
        City::create(['name' => 'زنجان', 'province_id' => $province->id]);
        City::create(['name' => 'ابهر', 'province_id' => $province->id]);
        City::create(['name' => 'خرمدره', 'province_id' => $province->id]);
        City::create(['name' => 'ماهنشان', 'province_id' => $province->id]);
        City::create(['name' => 'ایجرود', 'province_id' => $province->id]);
        City::create(['name' => 'طارم', 'province_id' => $province->id]);
        City::create(['name' => 'سلطانیه', 'province_id' => $province->id]);
        City::create(['name' => 'دندی', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'سمنان']);
        City::create(['name' => 'سمنان', 'province_id' => $province->id]);
        City::create(['name' => 'شاهرود', 'province_id' => $province->id]);
        City::create(['name' => 'دامغان', 'province_id' => $province->id]);
        City::create(['name' => 'گرمسار', 'province_id' => $province->id]);
        City::create(['name' => 'مهدی‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'آرادان', 'province_id' => $province->id]);
        City::create(['name' => 'میامی', 'province_id' => $province->id]);
        City::create(['name' => 'سرخه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'سیستان و بلوچستان']);
        City::create(['name' => 'زاهدان', 'province_id' => $province->id]);
        City::create(['name' => 'چابهار', 'province_id' => $province->id]);
        City::create(['name' => 'ایرانشهر', 'province_id' => $province->id]);
        City::create(['name' => 'خاش', 'province_id' => $province->id]);
        City::create(['name' => 'سراوان', 'province_id' => $province->id]);
        City::create(['name' => 'راسك', 'province_id' => $province->id]);
        City::create(['name' => 'میرجاوه', 'province_id' => $province->id]);
        City::create(['name' => 'کنارک', 'province_id' => $province->id]);
        City::create(['name' => 'دلگان', 'province_id' => $province->id]);
        City::create(['name' => 'زهک', 'province_id' => $province->id]);
        City::create(['name' => 'هیرمند', 'province_id' => $province->id]);
        City::create(['name' => 'نیک‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'سیب و سوران', 'province_id' => $province->id]);
        City::create(['name' => 'مهرستان', 'province_id' => $province->id]);
        City::create(['name' => 'قصرقند', 'province_id' => $province->id]);
        City::create(['name' => 'نیمروز', 'province_id' => $province->id]);
        City::create(['name' => 'فنوج', 'province_id' => $province->id]);
        City::create(['name' => 'تفتان', 'province_id' => $province->id]);
        City::create(['name' => 'بمپور', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'فارس']);
        City::create(['name' => 'شیراز', 'province_id' => $province->id]);
        City::create(['name' => 'مرودشت', 'province_id' => $province->id]);
        City::create(['name' => 'کازرون', 'province_id' => $province->id]);
        City::create(['name' => 'جهرم', 'province_id' => $province->id]);
        City::create(['name' => 'لار', 'province_id' => $province->id]);
        City::create(['name' => 'فسا', 'province_id' => $province->id]);
        City::create(['name' => 'نی‌ریز', 'province_id' => $province->id]);
        City::create(['name' => 'داراب', 'province_id' => $province->id]);
        City::create(['name' => 'ممسنی', 'province_id' => $province->id]);
        City::create(['name' => 'سپیدان', 'province_id' => $province->id]);
        City::create(['name' => 'قیروکارزین', 'province_id' => $province->id]);
        City::create(['name' => 'زرین‌دشت', 'province_id' => $province->id]);
        City::create(['name' => 'استهبان', 'province_id' => $province->id]);
        City::create(['name' => 'آباده', 'province_id' => $province->id]);
        City::create(['name' => 'لامرد', 'province_id' => $province->id]);
        City::create(['name' => 'خرامه', 'province_id' => $province->id]);
        City::create(['name' => 'خرم‌بید', 'province_id' => $province->id]);
        City::create(['name' => 'بوانات', 'province_id' => $province->id]);
        City::create(['name' => 'ارسنجان', 'province_id' => $province->id]);
        City::create(['name' => 'سروستان', 'province_id' => $province->id]);
        City::create(['name' => 'بیضا', 'province_id' => $province->id]);
        City::create(['name' => 'کوار', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'قزوین']);
        City::create(['name' => 'قزوین', 'province_id' => $province->id]);
        City::create(['name' => 'البرز', 'province_id' => $province->id]);
        City::create(['name' => 'آبیک', 'province_id' => $province->id]);
        City::create(['name' => 'تاکستان', 'province_id' => $province->id]);
        City::create(['name' => 'بوئین‌زهرا', 'province_id' => $province->id]);
        City::create(['name' => 'آوج', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'قم']);
        City::create(['name' => 'قم', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'کردستان']);
        City::create(['name' => 'سنندج', 'province_id' => $province->id]);
        City::create(['name' => 'سقز', 'province_id' => $province->id]);
        City::create(['name' => 'بانه', 'province_id' => $province->id]);
        City::create(['name' => 'قروه', 'province_id' => $province->id]);
        City::create(['name' => 'کامیاران', 'province_id' => $province->id]);
        City::create(['name' => 'بیجار', 'province_id' => $province->id]);
        City::create(['name' => 'دیواندره', 'province_id' => $province->id]);
        City::create(['name' => 'دهگلان', 'province_id' => $province->id]);
        City::create(['name' => 'مریوان', 'province_id' => $province->id]);
        City::create(['name' => 'سروآباد', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'کرمان']);
        City::create(['name' => 'کرمان', 'province_id' => $province->id]);
        City::create(['name' => 'رفسنجان', 'province_id' => $province->id]);
        City::create(['name' => 'سیرجان', 'province_id' => $province->id]);
        City::create(['name' => 'جیرفت', 'province_id' => $province->id]);
        City::create(['name' => 'زرند', 'province_id' => $province->id]);
        City::create(['name' => 'بم', 'province_id' => $province->id]);
        City::create(['name' => 'بردسیر', 'province_id' => $province->id]);
        City::create(['name' => 'راور', 'province_id' => $province->id]);
        City::create(['name' => 'کهنوج', 'province_id' => $province->id]);
        City::create(['name' => 'انار', 'province_id' => $province->id]);
        City::create(['name' => 'رودبار جنوب', 'province_id' => $province->id]);
        City::create(['name' => 'فهرج', 'province_id' => $province->id]);
        City::create(['name' => 'عنبرآباد', 'province_id' => $province->id]);
        City::create(['name' => 'نرماشیر', 'province_id' => $province->id]);
        City::create(['name' => 'ریگان', 'province_id' => $province->id]);
        City::create(['name' => 'قلعه‌گنج', 'province_id' => $province->id]);
        City::create(['name' => 'منوجان', 'province_id' => $province->id]);
        City::create(['name' => 'ارزوئیه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'کرمانشاه']);
        City::create(['name' => 'کرمانشاه', 'province_id' => $province->id]);
        City::create(['name' => 'اسلام‌آباد غرب', 'province_id' => $province->id]);
        City::create(['name' => 'سنقر', 'province_id' => $province->id]);
        City::create(['name' => 'سرپل‌ذهاب', 'province_id' => $province->id]);
        City::create(['name' => 'کنگاور', 'province_id' => $province->id]);
        City::create(['name' => 'هرسین', 'province_id' => $province->id]);
        City::create(['name' => 'جوانرود', 'province_id' => $province->id]);
        City::create(['name' => 'پاوه', 'province_id' => $province->id]);
        City::create(['name' => 'گیلانغرب', 'province_id' => $province->id]);
        City::create(['name' => 'قصر شیرین', 'province_id' => $province->id]);
        City::create(['name' => 'روانسر', 'province_id' => $province->id]);
        City::create(['name' => 'ثلاث باباجانی', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'کهگیلویه و بویراحمد']);
        City::create(['name' => 'یاسوج', 'province_id' => $province->id]);
        City::create(['name' => 'گچساران', 'province_id' => $province->id]);
        City::create(['name' => 'دهدشت', 'province_id' => $province->id]);
        City::create(['name' => 'چرام', 'province_id' => $province->id]);
        City::create(['name' => 'لیکک', 'province_id' => $province->id]);
        City::create(['name' => 'سی‌سخت', 'province_id' => $province->id]);
        City::create(['name' => 'لنده', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'گلستان']);
        City::create(['name' => 'گرگان', 'province_id' => $province->id]);
        City::create(['name' => 'گنبد کاووس', 'province_id' => $province->id]);
        City::create(['name' => 'علی‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'کردکوی', 'province_id' => $province->id]);
        City::create(['name' => 'بندرترکمن', 'province_id' => $province->id]);
        City::create(['name' => 'آق‌قلا', 'province_id' => $province->id]);
        City::create(['name' => 'کلاله', 'province_id' => $province->id]);
        City::create(['name' => 'مینودشت', 'province_id' => $province->id]);
        City::create(['name' => 'آزادشهر', 'province_id' => $province->id]);
        City::create(['name' => 'رامیان', 'province_id' => $province->id]);
        City::create(['name' => 'گمیشان', 'province_id' => $province->id]);
        City::create(['name' => 'مراوه‌تپه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'گیلان']);
        City::create(['name' => 'رشت', 'province_id' => $province->id]);
        City::create(['name' => 'لاهیجان', 'province_id' => $province->id]);
        City::create(['name' => 'انزلی', 'province_id' => $province->id]);
        City::create(['name' => 'لنگرود', 'province_id' => $province->id]);
        City::create(['name' => 'آستانه‌اشرفیه', 'province_id' => $province->id]);
        City::create(['name' => 'رودسر', 'province_id' => $province->id]);
        City::create(['name' => 'فومن', 'province_id' => $province->id]);
        City::create(['name' => 'صومعه‌سرا', 'province_id' => $province->id]);
        City::create(['name' => 'تالش', 'province_id' => $province->id]);
        City::create(['name' => 'رضوانشهر', 'province_id' => $province->id]);
        City::create(['name' => 'آستارا', 'province_id' => $province->id]);
        City::create(['name' => 'شفت', 'province_id' => $province->id]);
        City::create(['name' => 'ماسال', 'province_id' => $province->id]);
        City::create(['name' => 'املش', 'province_id' => $province->id]);
        City::create(['name' => 'سیاهکل', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'لرستان']);
        City::create(['name' => 'خرم‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'بروجرد', 'province_id' => $province->id]);
        City::create(['name' => 'دورود', 'province_id' => $province->id]);
        City::create(['name' => 'الیگودرز', 'province_id' => $province->id]);
        City::create(['name' => 'کوهدشت', 'province_id' => $province->id]);
        City::create(['name' => 'نورآباد', 'province_id' => $province->id]);
        City::create(['name' => 'الشتر', 'province_id' => $province->id]);
        City::create(['name' => 'ازنا', 'province_id' => $province->id]);
        City::create(['name' => 'پلدختر', 'province_id' => $province->id]);
        City::create(['name' => 'چگنی', 'province_id' => $province->id]);
        City::create(['name' => 'سپیددشت', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'مازندران']);
        City::create(['name' => 'ساری', 'province_id' => $province->id]);
        City::create(['name' => 'بابل', 'province_id' => $province->id]);
        City::create(['name' => 'آمل', 'province_id' => $province->id]);
        City::create(['name' => 'قائم‌شهر', 'province_id' => $province->id]);
        City::create(['name' => 'نوشهر', 'province_id' => $province->id]);
        City::create(['name' => 'بابلسر', 'province_id' => $province->id]);
        City::create(['name' => 'بهشهر', 'province_id' => $province->id]);
        City::create(['name' => 'چالوس', 'province_id' => $province->id]);
        City::create(['name' => 'نکا', 'province_id' => $province->id]);
        City::create(['name' => 'محمودآباد', 'province_id' => $province->id]);
        City::create(['name' => 'تنکابن', 'province_id' => $province->id]);
        City::create(['name' => 'جویبار', 'province_id' => $province->id]);
        City::create(['name' => 'فریدونکنار', 'province_id' => $province->id]);
        City::create(['name' => 'رامسر', 'province_id' => $province->id]);
        City::create(['name' => 'سوادکوه', 'province_id' => $province->id]);
        City::create(['name' => 'عباس‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'کلاردشت', 'province_id' => $province->id]);
        City::create(['name' => 'سوادکوه شمالی', 'province_id' => $province->id]);
        City::create(['name' => 'گلوگاه', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'مرکزی']);
        City::create(['name' => 'اراک', 'province_id' => $province->id]);
        City::create(['name' => 'ساوه', 'province_id' => $province->id]);
        City::create(['name' => 'خمین', 'province_id' => $province->id]);
        City::create(['name' => 'محلات', 'province_id' => $province->id]);
        City::create(['name' => 'دلیجان', 'province_id' => $province->id]);
        City::create(['name' => 'شازند', 'province_id' => $province->id]);
        City::create(['name' => 'تفرش', 'province_id' => $province->id]);
        City::create(['name' => 'آشتیان', 'province_id' => $province->id]);
        City::create(['name' => 'زرندیه', 'province_id' => $province->id]);
        City::create(['name' => 'خنداب', 'province_id' => $province->id]);
        City::create(['name' => 'کمیجان', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'هرمزگان']);
        City::create(['name' => 'بندرعباس', 'province_id' => $province->id]);
        City::create(['name' => 'بندر لنگه', 'province_id' => $province->id]);
        City::create(['name' => 'میناب', 'province_id' => $province->id]);
        City::create(['name' => 'قشم', 'province_id' => $province->id]);
        City::create(['name' => 'جاسک', 'province_id' => $province->id]);
        City::create(['name' => 'بندر خمیر', 'province_id' => $province->id]);
        City::create(['name' => 'رودان', 'province_id' => $province->id]);
        City::create(['name' => 'سیریک', 'province_id' => $province->id]);
        City::create(['name' => 'بستک', 'province_id' => $province->id]);
        City::create(['name' => 'پارسیان', 'province_id' => $province->id]);
        City::create(['name' => 'حاجی‌آباد', 'province_id' => $province->id]);
        City::create(['name' => 'ابوموسی', 'province_id' => $province->id]);
        City::create(['name' => 'بشاگرد', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'همدان']);
        City::create(['name' => 'همدان', 'province_id' => $province->id]);
        City::create(['name' => 'ملایر', 'province_id' => $province->id]);
        City::create(['name' => 'نهاوند', 'province_id' => $province->id]);
        City::create(['name' => 'تویسرکان', 'province_id' => $province->id]);
        City::create(['name' => 'کبودرآهنگ', 'province_id' => $province->id]);
        City::create(['name' => 'بهار', 'province_id' => $province->id]);
        City::create(['name' => 'رزن', 'province_id' => $province->id]);
        City::create(['name' => 'اسدآباد', 'province_id' => $province->id]);
        City::create(['name' => 'فامنین', 'province_id' => $province->id]);
        $province = Province::create(['name' => 'یزد']);
        City::create(['name' => 'یزد', 'province_id' => $province->id]);
        City::create(['name' => 'میبد', 'province_id' => $province->id]);
        City::create(['name' => 'اردکان', 'province_id' => $province->id]);
        City::create(['name' => 'تفت', 'province_id' => $province->id]);
        City::create(['name' => 'ابرکوه', 'province_id' => $province->id]);
        City::create(['name' => 'مهریز', 'province_id' => $province->id]);
        City::create(['name' => 'اشکذر', 'province_id' => $province->id]);
        City::create(['name' => 'بافق', 'province_id' => $province->id]);
        City::create(['name' => 'خاتم', 'province_id' => $province->id]);
        City::create(['name' => 'بهاباد', 'province_id' => $province->id]);

    }
}
